# attributes.py
attributes = {
    'Body': '0',
    'Strength': '0',
    'Agility': '0',
    'Intelligence': '0',
    'Charisma': '0',
    'Willpower': '0'
}
# skills.py
skills = ['Archery', 'Automatics', 'Blades', 'Clubs', 'Exotic Ranged Weapon', 'Exotic Melee Weapon',
          ]

# stats.py
stats = ['Essence', 'Magic', 'Resonance', 'Edge', 'Initiative', 'Matrix Initiative', 'Astral Initiative', ...]

# metatypes.py
metatype_type = {
    'Human': {'Priority': 'E', 'Body': '-', 'Strength': '-', 'Quickness': '-', 'Intelligence': '-', 'Willpower': '-', 'Charisma': '-', 'Running Multiplier': '×3', 'Other': '1:10 Karma Pool accumulation', 'Origin': 'anywhere'},
    'Dwarf': {'Priority': 'D', 'Body': '+1', 'Strength': '+2', 'Quickness': '-', 'Intelligence': '-', 'Willpower': '+1', 'Charisma': '-', 'Running Multiplier': '×2', 'Other': 'Thermographic vision, Resistance (+2 Body) to any disease or toxin', 'Origin': 'anywhere'},
    'Gnome': {'Priority': 'D', 'Body': '+1', 'Strength': '+1', 'Quickness': '-', 'Intelligence': '-', 'Willpower': '+2', 'Charisma': '-', 'Running Multiplier': '×2', 'Other': 'Thermographic vision', 'Origin': 'Central Europe, Asia Minor'},
    'Koborokuru': {'Priority': 'C', 'Body': '+1', 'Strength': '+2', 'Quickness': '-', 'Intelligence': '-', 'Willpower': '+1', 'Charisma': '-', 'Running Multiplier': '×3', 'Other': 'Thermographic vision, Resistance (+2 Body) to any disease or toxin, Natural Immunity Edge (1 point and 3 point), ×3 running multiplier', 'Origin': 'Japan'},
    'Menehune': {'Priority': 'D', 'Body': '+2', 'Strength': '+1', 'Quickness': '-', 'Intelligence': '-', 'Willpower': '+1', 'Charisma': '-', 'Running Multiplier': '×2', 'Other': 'Thermographic vision, Resistance (+2 Body) to any disease or toxin', 'Origin': 'Pacific Islands'},
    'Elf': {'Priority': 'C', 'Body': '-', 'Strength': '-', 'Quickness': '+1', 'Intelligence': '-', 'Willpower': '-', 'Charisma': '+2', 'Running Multiplier': '×3', 'Other': 'Low-Light Vision', 'Origin': 'anywhere'},
    'Night One': {'Priority': 'C', 'Body': '-', 'Strength': '-', 'Quickness': '+2', 'Intelligence': '-', 'Willpower': '-', 'Charisma': '+2', 'Running Multiplier': '×3', 'Other': 'Mild allergy (Sunlight), Low-Light Vision', 'Origin': 'Central Europe'},
    'Wakyambi': {'Priority': 'C', 'Body': '-', 'Strength': '-', 'Quickness': '-', 'Intelligence': '-', 'Willpower': '+1', 'Charisma': '+2', 'Running Multiplier': '×3', 'Other': 'Low-Light Vision', 'Origin': 'Sub-Saharan Africa'},
    'Ork': {'Priority': 'D', 'Body': '+3', 'Strength': '+2', 'Quickness': '-', 'Intelligence': '-1', 'Willpower': '-', 'Charisma': '-1', 'Running Multiplier': '×3', 'Other': 'Low-Light Vision', 'Origin': 'anywhere'},
    'Hobgoblin': {'Priority': 'D', 'Body': '+2', 'Strength': '+1', 'Quickness': '-', 'Intelligence': '-', 'Willpower': '-', 'Charisma': '-1', 'Running Multiplier': '×3', 'Other': 'Low-Light Vision', 'Origin': 'Middle East'},
    'Ogre': {'Priority': 'D', 'Body': '+3', 'Strength': '+2', 'Quickness': '-', 'Intelligence': '-1', 'Willpower': '-', 'Charisma': '-', 'Running Multiplier': '×3', 'Other': '-', 'Origin': 'Continental Europe'},
    'Oni': {'Priority': 'D', 'Body': '+2', 'Strength': '+2', 'Quickness': '-', 'Intelligence': '-1', 'Willpower': '+1', 'Charisma': '-1', 'Running Multiplier': '×3', 'Other': 'Low-Light Vision', 'Origin': 'Japan'},
    'Satyr': {'Priority': 'D', 'Body': '+3', 'Strength': '+2', 'Quickness': '-1', 'Intelligence': '-1', 'Willpower': '+1', 'Charisma': '-1', 'Running Multiplier': '×4', 'Other': 'Low-Light Vision, ×4 running multiplier', 'Origin': 'Mediterranean'},
    'Troll': {'Priority': 'C', 'Body': '+5', 'Strength': '+4', 'Quickness': '-1', 'Intelligence': '-2', 'Willpower': '-', 'Charisma': '-2', 'Running Multiplier': '×3', 'Other': 'Thermographic Vision, +1 Reach for Armed/Unarmed Combat, Dermal Armor (+1 Body)', 'Origin': 'anywhere'},
    'Cyclops': {'Priority': 'C', 'Body': '+5', 'Strength': '+6', 'Quickness': '-1', 'Intelligence': '-2', 'Willpower': '-', 'Charisma': '-2', 'Running Multiplier': '×3', 'Other': '+1 Reach for Armed/Unarmed Combat, +2 TN for melee attacks', 'Origin': 'Mediterranean'},
    'Fomori': {'Priority': 'C', 'Body': '+4', 'Strength': '+3', 'Quickness': '-1', 'Intelligence': '-2', 'Willpower': '-', 'Charisma': '-', 'Running Multiplier': '×3', 'Other': 'Thermographic Vision, +1 Reach for Armed/Unarmed Combat', 'Origin': 'British Isles'},
    'Giant': {'Priority': 'C', 'Body': '+5', 'Strength': '+5', 'Quickness': '-1', 'Intelligence': '-2', 'Willpower': '-', 'Charisma': '-', 'Running Multiplier': '×3', 'Other': 'Thermographic Vision, +1 Reach for Armed/Unarmed Combat', 'Origin': 'Scandinavia, British Isles, Iceland'},
    'Minotaur': {'Priority': 'C', 'Body': '+4', 'Strength': '+3', 'Quickness': '-1', 'Intelligence': '-1', 'Willpower': '-', 'Charisma': '-', 'Running Multiplier': '×3', 'Other': 'Thermographic Vision, +1 Reach for Armed/Unarmed Combat, Dermal Armor (+1 Body)', 'Origin': 'Mediterranean'}
}

selected_metatype_data = {
        'Human': {
        'Priority': 'E',
        'Body': '-',
        'Strength': '-',
        'Quickness': '-',
        'Intelligence': '-',
        'Willpower': '-',
        'Charisma': '-',
        'Running Multiplier': '×3',
        'Other': '1:10 Karma Pool accumulation',
        'Origin': 'anywhere',
        'Average Height': '170 cm',
        'Average Mass': '70 kg',
        'Height Range': '130 cm – 221 cm',
        'Mass Range': '31 kg – 153 kg',
        'Life Expectancy': '55 years',
        'Percentage Population': '81%'
    },
    'Dwarf': {
        'Priority': 'D',
        'Body': '+1',
        'Strength': '+2',
        'Quickness': '-',
        'Intelligence': '-',
        'Willpower': '+1',
        'Charisma': '-',
        'Running Multiplier': '×2',
        'Other': 'Thermographic vision, Resistance (+2 Body) to any disease or toxin',
        'Origin': 'anywhere',
        'Average Height': '120 cm',
        'Average Mass': '44 kg',
        'Height Range': '95 cm – 151 cm',
        'Mass Range': '22 kg – 89 kg',
        'Life Expectancy': 'estimated at 120–150 years',
        'Percentage Population': '3%'
    },
    'Elf': {
        'Priority': 'C',
        'Body': '-',
        'Strength': '-',
        'Quickness': '+1',
        'Intelligence': '-',
        'Willpower': '-',
        'Charisma': '+2',
        'Running Multiplier': '×3',
        'Other': 'Low-Light Vision',
        'Origin': 'anywhere',
        'Average Height': '190 cm',
        'Average Mass': '78 kg',
        'Height Range': '146 cm – 247 cm',
        'Mass Range': '35 kg – 171 kg',
        'Life Expectancy': 'estimated at 300–500 years',
        'Percentage Population': '5%'
    },
    'Ork': {
        'Priority': 'D',
        'Body': '+3',
        'Strength': '+2',
        'Quickness': '-',
        'Intelligence': '-1',
        'Willpower': '-',
        'Charisma': '-1',
        'Running Multiplier': '×3',
        'Other': 'Low-Light Vision',
        'Origin': 'anywhere',
        'Average Height': '190 cm',
        'Average Mass': '125 kg',
        'Height Range': '147 cm – 244 cm',
        'Mass Range': '58 kg – 266 kg',
        'Life Expectancy': '38 years',
        'Percentage Population': '9%'
    },
    'Troll': {
        'Priority': 'C',
        'Body': '+5',
        'Strength': '+4',
        'Quickness': '-1',
        'Intelligence': '-2',
        'Willpower': '-',
        'Charisma': '-2',
        'Running Multiplier': '×3',
        'Other': 'Thermographic Vision, +1 Reach for Armed/Unarmed Combat, Dermal Armor (+1 Body)',
        'Origin': 'anywhere',
        'Average Height': '280 cm',
        'Average Mass': '491 kg',
        'Height Range': '219 cm – 357 cm',
        'Mass Range': '236 kg – 1017 kg',
        'Life Expectancy': '50 years',
        'Percentage Population': '2%'
    }
}
# priorities.py

priority_data = {
    'A': {'Races': {'Dwarf': 13, 'Ork': 13, 'Troll': 13}, 'Attributes': 24, 'Skills': 32,
          'Magic/Resonance': {'Full': 4, 'Aspected': 5, 'Mystic Adept': 4, 'Adept': 4, 'Technomancer': 4},
          'Resources': 450000},
    'B': {'Races': {'Dwarf': 11, 'Elf': 11, 'Ork': 11, 'Troll': 11}, 'Attributes': 16, 'Skills': 24,
          'Magic/Resonance': {'Full': 3, 'Aspected': 4, 'Mystic Adept': 3, 'Adept': 3, 'Technomancer': 3},
          'Resources': 275000},
    'C': {'Races': {'Dwarf': 9, 'Elf': 9, 'Human': 9, 'Ork': 9, 'Troll': 9}, 'Attributes': 12, 'Skills': 20,
          'Magic/Resonance': {'Full': 2, 'Aspected': 3, 'Mystic Adept': 2, 'Adept': 2, 'Technomancer': 2},
          'Resources': 150000},
    'D': {'Races': {'Dwarf': 4, 'Elf': 4, 'Human': 4, 'Ork': 4, 'Troll': 4}, 'Attributes': 8, 'Skills': 16,
          'Magic/Resonance': {'Full': 1, 'Aspected': 2, 'Mystic Adept': 1, 'Adept': 1, 'Technomancer': 1},
          'Resources': 50000},
    'E': {'Races': {'Dwarf': 1, 'Elf': 1, 'Human': 1, 'Ork': 1, 'Troll': 1}, 'Attributes': 2, 'Skills': 10,
          'Magic/Resonance': 'Mundane', 'Resources': 8000}
}


# List of spell schools
spell_schools = ['Combat', 'Detection', 'Health', 'Illusion', 'Manipulation', 'Drain', 'Enchantment', 'Geomancy']

# spell_list.py

# Dictionary of spell lists
spell_list = {
    'Combat': ['Ball Lightning', 'Clout', 'Flamethrower', 'Ice Spear', 'Lightning Bolt', 'Manaball', 'Manabolt', 'Powerbolt'],
    'Detection': ['Analyze Device', 'Analyze Truth', 'Assensing', 'Clairaudience', 'Clairvoyance', 'Detect Enemies', 'Detect Individual', 'Detect Life'],
    'Health': ['Decrease Attribute', 'Heal', 'Increase Attribute', 'Increase Reflexes', 'Stabilize'],
    'Illusion': ['Chaotic World', 'Control Thoughts', 'Improved Invisibility', 'Mask', 'Physical Mask', 'Trid Phantasm'],
    'Manipulation': ['Analyze Device', 'Control Actions', 'Control Thoughts', 'Fling', 'Influence', 'Levitate', 'Mob Mind'],
    'Enchantment': ['Armor', 'Bind', 'Elemental Barrier', 'Magic Fingers', 'Trid Phantasm'],
    'Drain': ['Alleviate Addiction', 'Death Touch', 'Mind Probe', 'Psychic Surgery'],
    'Geomancy': ['Elemental Manipulation', 'Plant Control', 'Shape Earth', 'Water Spirit']
}
#
# weapons = [
#     {'Name': 'Defiance EX Shocker', 'Type': 'Taser', 'Scale': 'Character', 'Skill': 'Firearms', 'Mode': 'SS', 'RC': '-', 'Cost': '250', 'Availability': '1', 'Ammunition': '4(m)', 'Damage': '6D (Stun)'},
#     {'Name': 'Yamaha Pulsar', 'Type': 'Taser', 'Scale': 'Character', 'Skill': 'Firearms', 'Mode': 'SA', 'RC': '-', 'Cost': '180', 'Availability': '1', 'Ammunition': '4(m)', 'Damage': '4D+2 (Stun)'},
#     {'Name': 'Fichetti Tiffani Needler', 'Type': 'Hold-Out Pistol', 'Scale': 'Character', 'Skill': 'Firearms', 'Mode': 'SA', 'RC': '-', 'Cost': '1,000', 'Availability': '2; R', 'Ammunition': '4(c)', 'Damage': '5D+1 (flechette)'},
#     {'Name': 'Streetline Special', 'Type': 'Hold-Out Pistol', 'Scale': 'Character', 'Skill': 'Firearms', 'Mode': 'SA', 'RC': '-', 'Cost': '120', 'Availability': '1; R', 'Ammunition': '6(c)', 'Damage': '4D'},
#     {'Name': 'Walther Palm Pistol', 'Type': 'Hold-Out Pistol', 'Scale': 'Character', 'Skill': 'Firearms', 'Mode': 'SS/BF', 'RC': '-', 'Cost': '180', 'Availability': '1; R', 'Ammunition': '2(b)', 'Damage': '4D+2'},
#     {'Name': 'Ares Light Fire 70', 'Type': 'Light Pistol', 'Scale': 'Character', 'Skill': 'Firearms', 'Mode': 'SA', 'RC': '-', 'Cost': '200', 'Availability': '1; R', 'Ammunition': '16(c)', 'Damage': '4D'},
#     {'Name': 'Ares Light Fire 75', 'Type': 'Light Pistol', 'Scale': 'Character', 'Skill': 'Firearms', 'Mode': 'SA', 'RC': '-', 'Cost': '1,250', 'Availability': '2; X', 'Ammunition': '16(c)', 'Damage': '4D'},
#     {'Name': 'Beretta 201T', 'Type': 'Light Pistol', 'Scale': 'Character', 'Skill': 'Firearms', 'Mode': 'SA/BF', 'RC': '(1)', 'Cost': '210', 'Availability': '2; R', 'Ammunition': '21(c)', 'Damage': '4D'},
#     {'Name': 'Colt America L36', 'Type': 'Light Pistol', 'Scale': 'Character', 'Skill': 'Firearms', 'Mode': 'SA', 'RC': '-', 'Cost': '320', 'Availability': '1; R', 'Ammunition': '11(c)', 'Damage': '4D+2'},
#     {'Name': 'Fichetti Security 600', 'Type': 'Light Pistol', 'Scale': 'Character', 'Skill': 'Firearms', 'Mode': 'SA', 'RC': '-', 'Cost': '350', 'Availability': '2; R', 'Ammunition': '30(c)', 'Damage': '4D+2'},
#     {'Name': 'Taurus Omni-6', 'Type': 'Light Pistol', 'Scale': 'Character', 'Skill': 'Firearms', 'Mode': 'SA/SS', 'RC': '(1)', 'Cost': '300', 'Availability': '1; R', 'Ammunition': '6(cy)', 'Damage': '4D / 4D+2'},
#     {'Name': 'Ares Predator V', 'Type': 'Heavy Pistol', 'Scale': 'Character', 'Skill': 'Firearms', 'Mode': 'SA', 'RC': '-', 'Cost': '725', 'Availability': '2; R', 'Ammunition': '15(c)', 'Damage': '5D+1'},
#     {'Name': 'Ares Viper Slivergun', 'Type': 'Heavy Pistol', 'Scale': 'Character', 'Skill': 'Firearms', 'Mode': 'SA/BF', 'RC': '-', 'Cost': '380', 'Availability': '3; X', 'Ammunition': '30(c)', 'Damage': '6D (flechette)'},
#     {'Name': 'Browning Ultra-Power', 'Type': 'Heavy Pistol', 'Scale': 'Character', 'Skill': 'Firearms', 'Mode': 'SA', 'RC': '-', 'Cost': '640', 'Availability': '1; R', 'Ammunition': '10(c)', 'Damage': '5D+1'},
#     {'Name': 'Colt Government 2066', 'Type': 'Heavy Pistol', 'Scale': 'Character', 'Skill': 'Firearms', 'Mode': 'SA', 'RC': '-', 'Cost': '425', 'Availability': '2; R', 'Ammunition': '14(c)', 'Damage': '4D+2'},
#     {'Name': 'Remington Roomsweeper', 'Type': 'Heavy Pistol', 'Scale': 'Character', 'Skill': 'Firearms', 'Mode': 'SA', 'RC': '-', 'Cost': '250', 'Availability': '2; R', 'Ammunition': '8(m)', 'Damage': '4D+2'},
#     {'Name': 'Ruger Super Warhawk', 'Type': 'Heavy Pistol', 'Scale': 'Character', 'Skill': 'Firearms', 'Mode': 'SS', 'RC': '-', 'Cost': '400', 'Availability': '1; R', 'Ammunition': '6(cy)', 'Damage': '6D'},
#     {'Name': 'Ares Crusader II', 'Type': 'Machine Pistol', 'Scale': 'Character', 'Skill': 'Firearms', 'Mode': 'SA/BF', 'RC': '2', 'Cost': '830', 'Availability': '3; R', 'Ammunition': '40(c)', 'Damage': '4D+2'},
#     {'Name': 'Ceska Black Scorpion', 'Type': 'Machine Pistol', 'Scale': 'Character', 'Skill': 'Firearms', 'Mode': 'SA/BF', 'RC': '(1)', 'Cost': '270', 'Availability': '2; R', 'Ammunition': '35(c)', 'Damage': '4D'},
#     {'Name': 'Steyr TMP', 'Type': 'Machine Pistol', 'Scale': 'Character', 'Skill': 'Firearms', 'Mode': 'SA/BF/FA', 'RC': '-', 'Cost': '350', 'Availability': '3; R', 'Ammunition': '30(c)', 'Damage': '4D+2'},
#     {'Name': 'Colt Cobra TZ-120', 'Type': 'Submachine Gun', 'Scale': 'Character', 'Skill': 'Firearms', 'Mode': 'SA/BF/FA', 'RC': '2 (3)', 'Cost': '660', 'Availability': '2; R', 'Ammunition': '32(c)', 'Damage': '4D+2'},
#     {'Name': 'FN P93 Praetor', 'Type': 'Submachine Gun', 'Scale': 'Character', 'Skill': 'Firearms', 'Mode': 'SA/BF/FA', 'RC': '1 (2)', 'Cost': '900', 'Availability': '4; X', 'Ammunition': '50(c)', 'Damage': '5D+1'},
#     {'Name': 'HK-227', 'Type': 'Submachine Gun', 'Scale': 'Character', 'Skill': 'Firearms', 'Mode': 'SA/BF/FA', 'RC': '(1)', 'Cost': '730', 'Availability': '3; R', 'Ammunition': '28(c)', 'Damage': '4D+2'},
#     {'Name': 'Ingram Smartgun X', 'Type': 'Submachine Gun', 'Scale': 'Character', 'Skill': 'Firearms', 'Mode': 'BF/FA', 'RC': '2', 'Cost': '800', 'Availability': '2; R', 'Ammunition': '32(c)', 'Damage': '5D+1'},
#     {'Name': 'SCK Model 100', 'Type': 'Submachine Gun', 'Scale': 'Character', 'Skill': 'Firearms', 'Mode': 'SA/BF', 'RC': '(1)', 'Cost': '875', 'Availability': '2; R', 'Ammunition': '30(c)', 'Damage': '5D+1'},
#     {'Name': 'Uzi IV', 'Type': 'Submachine Gun', 'Scale': 'Character', 'Skill': 'Firearms', 'Mode': 'BF', 'RC': '(1)', 'Cost': '450', 'Availability': '1; R', 'Ammunition': '24(c)', 'Damage': '4D+2'},
#     {'Name': 'AK-97', 'Type': 'Assault Rifle', 'Scale': 'Character', 'Skill': 'Firearms', 'Mode': 'SA/BF/FA', 'RC': '-', 'Cost': '950', 'Availability': '1; R', 'Ammunition': '38(c)', 'Damage': '6D+2'},
#     {'Name': 'Ares Alpha', 'Type': 'Assault Rifle', 'Scale': 'Character', 'Skill': 'Firearms', 'Mode': 'SA/BF/FA', 'RC': '2', 'Cost': '2,650', 'Availability': '4; X', 'Ammunition': '42(c)', 'Damage': '7D+1'},
#     {'Name': 'Colt M23', 'Type': 'Assault Rifle', 'Scale': 'Character', 'Skill': 'Firearms', 'Mode': 'SA/BF/FA', 'RC': '-', 'Cost': '550', 'Availability': '1; R', 'Ammunition': '40(c)', 'Damage': '6D'},
#     {'Name': 'FN HAR', 'Type': 'Assault Rifle', 'Scale': 'Character', 'Skill': 'Firearms', 'Mode': 'SA/BF/FA', 'RC': '2', 'Cost': '1,500', 'Availability': '3; R', 'Ammunition': '35(c)', 'Damage': '6D+2'},
#     {'Name': 'Yamaha Raiden', 'Type': 'Assault Rifle', 'Scale': 'Character', 'Skill': 'Firearms', 'Mode': 'BF/FA', 'RC': '1', 'Cost': '2,600', 'Availability': '5; X', 'Ammunition': '60(c)', 'Damage': '7D+1'},
#     {'Name': 'Ares Desert Strike', 'Type': 'Sniper Rifle', 'Scale': 'Speeder', 'Skill': 'Firearms', 'Mode': 'SA', 'RC': '(1)', 'Cost': '17,500', 'Availability': '3; X', 'Ammunition': '14(c)', 'Damage': '4D+1'},
#     {'Name': 'Cavalier Arms Crockett EBR', 'Type': 'Sniper Rifle', 'Scale': 'Speeder', 'Skill': 'Firearms', 'Mode': 'SA/BF', 'RC': '(1)', 'Cost': '10,300', 'Availability': '4; X', 'Ammunition': '20(c)', 'Damage': '4D'},
#     {'Name': 'Ranger Arms SM–5', 'Type': 'Sniper Rifle', 'Scale': 'Speeder', 'Skill': 'Firearms', 'Mode': 'SA', 'RC': '(1)', 'Cost': '28,000', 'Availability': '5; X', 'Ammunition': '15(c)', 'Damage': '4D+2'},
#     {'Name': 'Remington 950', 'Type': 'Sniper Rifle', 'Scale': 'Speeder', 'Skill': 'Firearms', 'Mode': 'SS', 'RC': '-', 'Cost': '2,100', 'Availability': '1; R', 'Ammunition': '5(m)', 'Damage': '4D'},
#     {'Name': 'Ruger 100', 'Type': 'Sniper Rifle', 'Scale': 'Speeder', 'Skill': 'Firearms', 'Mode': 'SA', 'RC': '(1)', 'Cost': '1,300', 'Availability': '1; R', 'Ammunition': '8(m)', 'Damage': '3D+2'},
#     {'Name': 'Defiance T–250', 'Type': 'Shotgun', 'Scale': 'Character', 'Skill': 'Firearms', 'Mode': 'SS/SA', 'RC': '-', 'Cost': '450', 'Availability': '1; R', 'Ammunition': '5(m)', 'Damage': '6D+2'},
#     {'Name': 'Enfield AS-7', 'Type': 'Shotgun', 'Scale': 'Character', 'Skill': 'Firearms', 'Mode': 'SA/BF', 'RC': '-', 'Cost': '1,100', 'Availability': '4; X', 'Ammunition': '10(c) or 24(d)', 'Damage': '8D+2'},
#     {'Name': 'PJSS Model 55', 'Type': 'Shotgun', 'Scale': 'Character', 'Skill': 'Firearms', 'Mode': 'SS', 'RC': '(1)', 'Cost': '1,000', 'Availability': '3; R', 'Ammunition': '2(b)', 'Damage': '7D+1'},
#     {'Name': 'Ares S-III Super Squirt', 'Type': 'Squirt Gun', 'Scale': 'Character', 'Skill': 'Firearms', 'Mode': 'SA', 'RC': '-', 'Cost': '950', 'Availability': '2; R', 'Ammunition': '20(c)', 'Damage': 'Chemical'},
#     {'Name': 'Fichetti Pain Inducer', 'Type': 'Special', 'Scale': 'Character', 'Skill': 'Firearms', 'Mode': 'SS', 'RC': '-', 'Cost': '5,000', 'Availability': '4; R', 'Ammunition': 'Special', 'Damage': 'Special'},
#     {'Name': 'Parashield Dart Pistol', 'Type': 'Dart Pistol', 'Scale': 'Character', 'Skill': 'Firearms', 'Mode': 'SA', 'RC': '-', 'Cost': '600', 'Availability': '1; R', 'Ammunition': '5(c)', 'Damage': 'As Drug/Toxin'},
#     {'Name': 'Parashield Dart Rifle', 'Type': 'Dart Pistol', 'Scale': 'Character', 'Skill': 'Firearms', 'Mode': 'SA', 'RC': '0', 'Cost': '1,200', 'Availability': '2; R', 'Ammunition': '6(m)', 'Damage': 'As Drug/Toxin'},
#     {'Name': 'Ingram Valiant', 'Type': 'Machine Gun', 'Scale': 'Character', 'Skill': 'Firearms', 'Mode': 'BF/FA', 'RC': '2 (3)', 'Cost': '5,800', 'Availability': '4; X', 'Ammunition': '50(c) or 100(belt)', 'Damage': '6D'},
#     {'Name': 'Stoner-Ares M202', 'Type': 'Machine Gun', 'Scale': 'Character', 'Skill': 'Firearms', 'Mode': 'FA', 'RC': '-', 'Cost': '7,000', 'Availability': '4; X', 'Ammunition': '50(c) or 100(belt)', 'Damage': '6D+2'},
#     {'Name': 'RPK HMG', 'Type': 'Machine Gun', 'Scale': 'Character', 'Skill': 'Firearms', 'Mode': 'FA', 'RC': '(6)', 'Cost': '16,300', 'Availability': '4; X', 'Ammunition': '50(c) or 100(belt)', 'Damage': '8D'},
#     {'Name': 'Ares Antioch-2', 'Type': 'Grenade Launcher', 'Scale': 'Character', 'Skill': 'Missile Weapons', 'Mode': 'SS', 'RC': '-', 'Cost': '3,200', 'Availability': '3; X', 'Ammunition': '8(m)', 'Damage': 'Grenade'},
#     {'Name': 'ArmTech MGL-12', 'Type': 'Grenade Launcher', 'Scale': 'Character', 'Skill': 'Missile Weapons', 'Mode': 'SA', 'RC': '-', 'Cost': '5,000', 'Availability': '3; X', 'Ammunition': '12(c)', 'Damage': 'Grenade'},
#     {'Name': 'Aztechnology Striker', 'Type': 'Missile Launcher', 'Scale': 'Character', 'Skill': 'Missile Weapons', 'Mode': 'SS', 'RC': '-', 'Cost': '1,200', 'Availability': '3; X', 'Ammunition': '1(ml)', 'Damage': 'Missile'},
#     {'Name': 'Krime Cannon', 'Type': 'Assault Cannon', 'Scale': 'Walker', 'Skill': 'Firearms', 'Mode': 'SA', 'RC': '(1)', 'Cost': '21,000', 'Availability': '6; X', 'Ammunition': '6(m)', 'Damage': '4D+1'},
#     {'Name': 'Onotari Interceptor', 'Type': 'Missile Launcher', 'Scale': 'Character', 'Skill': 'Missile Weapons', 'Mode': 'SS', 'RC': '-', 'Cost': '14,000', 'Availability': '6; X', 'Ammunition': '2(ml)', 'Damage': 'Missile'},
#     {'Name': 'Panther XXL', 'Type': 'Assault Cannon', 'Scale': 'Walker', 'Skill': 'Firearms', 'Mode': 'SS', 'RC': '-', 'Cost': '43,000', 'Availability': '6; X', 'Ammunition': '15(c)', 'Damage': '4D+2'}
#     {'Name': 'Ares Monosword', 'Concealability': 3, 'Reach': 1, 'Damage': '(STR+3)M', 'Weight': 2, 'Base Price': '2,500¥', 'Legality': '4-B', 'Availibilty': '4/24 hrs', 'Street Index': 1.0},
#     {'Name': 'AZ-I50 Stun Baton', 'Concealability': 5, 'Reach': 8, 'Damage': '8S Stun', 'Weight': 1, 'Base Price': '1,500¥', 'Legality': '5-C', 'Availibilty': '3/36 hrs', 'Street Index': 2.0},
#     {'Name': 'Centurion Laser Axe', 'Concealability': 2, 'Reach': 1, 'Damage': '(STR)S', 'Weight': 5.2, 'Base Price': '3,500¥', 'Legality': '4-B', 'Availibilty': '3/24 hrs', 'Street Index': 0.5},
#     {'Name': 'Club', 'Concealability': 5, 'Reach': 1, 'Damage': '(STR+1)M Stun', 'Weight': 1, 'Base Price': '10¥', 'Legality': '6-C', 'Availibilty': '2/6 hrs', 'Street Index': 1.0},
#     {'Name': 'Combat Axe', 'Concealability': 2, 'Reach': 2, 'Damage': '(STR)S', 'Weight': 2.0, 'Base Price': '750¥', 'Legality': '3-B', 'Availibilty': '3/24 hrs', 'Street Index': 2.0},
#     {'Name': 'Thrusting Point', 'Concealability': '(STR+2)L', 'Reach': '', 'Damage': '', 'Weight': '', 'Base Price': '', 'Legality': '', 'Availibilty': '', 'Street Index': ''},
#     {'Name': 'Forearm Snap Blades', 'Concealability': 7, 'Reach': '(STR)M', 'Damage': '', 'Weight': 1.5, 'Base Price': '850¥', 'Legality': '4-B', 'Availibilty': '4/48 hrs', 'Street Index': 2.0},
#     {'Name': 'Hand Razors, Retractable', 'Concealability': 10, 'Reach': '(STR)L', 'Damage': '', 'Weight': '', 'Base Price': '9,000¥', 'Legality': '3-B', 'Availibilty': '3/72 hrs', 'Street Index': 1.0},
#     {'Name': 'Hand Razors. Extended', 'Concealability': 'NA', 'Reach': '(STR)L', 'Damage': '', 'Weight': '', 'Base Price': '4,500', 'Legality': '3-B', 'Availibilty': '3/72 hrs', 'Street Index': 1.0},
#     {'Name': 'Improved Blade', 'Concealability': 'As razor', 'Reach': '(STR+2)L', 'Damage': '+8,500¥', 'Weight': '', 'Base Price': '', 'Legality': '3-B', 'Availibilty': '6/72 hrs', 'Street Index': 1.0},
#     {'Name': 'Katana', 'Concealability': 3, 'Reach': 1, 'Damage': '(STR+3)M', 'Weight': 1, 'Base Price': '1,000¥', 'Legality': '5-B', 'Availibilty': '4/48 hrs', 'Street Index': 2.0},
#     {'Name': 'Knife', 'Concealability': 8, 'Reach': '(STR)L', 'Damage': '', 'Weight': 0.5, 'Base Price': '30¥', 'Legality': '8-A', 'Availibilty': '2/4 hrs', 'Street Index': 0.75},
#     {'Name': 'Monofilament Whip', 'Concealability': 10, 'Reach': 2, 'Damage': '10S', 'Weight': '', 'Base Price': '3,000¥', 'Legality': '1-J', 'Availibilty': '24/14 days', 'Street Index': 3.0},
#     {'Name': 'Pole Arm', 'Concealability': 2, 'Reach': 2, 'Damage': '(STR)S', 'Weight': 4, 'Base Price': '500¥', 'Legality': '3-B', 'Availibilty': '4/48 hrs', 'Street Index': 2.0},
#     {'Name': 'Sap', 'Concealability': 8, 'Reach': 1, 'Damage': '(STR+1)M Stun', 'Weight': 1, 'Base Price': '10¥', 'Legality': '5-C', 'Availibilty': '2/6 hrs', 'Street Index': 1.0},
#     {'Name': 'Shock Glove', 'Concealability': 9, 'Reach': '', 'Damage': '7S Stun', 'Weight': 0.5, 'Base Price': '950¥', 'Legality': '5-B', 'Availibilty': '5/48 hrs', 'Street Index': 2.0},
#     {'Name': 'Spurs', 'Concealability': 'NA', 'Reach': '(STR)M', 'Damage': '', 'Weight': '', 'Base Price': '7,000¥', 'Legality': '3-B', 'Availibilty': '3/72 hrs', 'Street Index': 1.0},
#     {'Name': 'Spurs, Retractable', 'Concealability': 9, 'Reach': '(STR)M', 'Damage': '', 'Weight': '', 'Base Price': '11,500¥', 'Legality': '3-B', 'Availibilty': '3/7Z hrs', 'Street Index': 1.0},
#     {'Name': 'Staff', 'Concealability': 2, 'Reach': 2, 'Damage': '(STR+2)M Stun', 'Weight': 2, 'Base Price': '50¥', 'Legality': '8-C', 'Availibilty': '3/24 hrs', 'Street Index': 1.0},
#     {'Name': 'Stun Baton', 'Concealability': 4, 'Reach': '(STR+2)M Srun', 'Damage': '750¥', 'Weight': '', 'Base Price': '5-C', 'Legality': '3/36 hrs', 'Availibilty': 1.0},
#     {'Name': 'Survival Knife', 'Concealability': 6, 'Reach': '(STR+2)L', 'Damage': '', 'Weight': 0.75, 'Base Price': '450¥', 'Legality': '6-A', 'Availibilty': '3/6 hrs', 'Street Index': 1.0},
#     {'Name': 'Sword', 'Concealability': 4, 'Reach': 1, 'Damage': '(STR+ 2)M', 'Weight': 1, 'Base Price': '500¥', 'Legality': '4-B', 'Availibilty': '3/24 hrs', 'Street Index': 1.0}
#     {'Name': 'Bow', 'Concealability': 3, 'Strength': '1+ (STR+2)M', 'MinDamage': 1, 'Weight': 1, 'Base Price': '300¥', 'Legality': '5-D', 'Availability': '3/36 hrs', 'Street Index': 1.0},
#     {'Name': 'Arrows', 'Concealability': 3, 'Strength': 'as bow', 'MinDamage': '', 'Weight': 0.1, 'Base Price': '10¥', 'Legality': '10-D', 'Availability': '3/36 hrs', 'Street Index': 1.0},
#     {'Name': 'Ranger-X Compound Bow', 'Concealability': 4, 'Strength': '2+ (STR+4)M', 'MinDamage': '', 'Weight': 1.5, 'Base Price': '550¥', 'Legality': '5-D', 'Availability': '4/36 hrs', 'Street Index': 2.0},
#     {'Name': 'Ranger-X Precision Arrows', 'Concealability': 3, 'Strength': 'NA', 'MinDamage': 'As bow', 'Weight': 0.08, 'Base Price': '18¥', 'Legality': '10-D', 'Availability': '4/36 hrs', 'Street Index': 2.0},
#     {'Name': 'Crossbow Light', 'Concealability': 2, 'Strength': '1+ (STR+2)L', 'MinDamage': '', 'Weight': 2, 'Base Price': '300¥', 'Legality': '6-D', 'Availability': '4/36 hrs', 'Street Index': 1.0},
#     {'Name': 'Crossbow Medium', 'Concealability': 2, 'Strength': '2+ (STR+2)M', 'MinDamage': '', 'Weight': 3, 'Base Price': '400¥', 'Legality': '6-D', 'Availability': '5/36 hrs', 'Street Index': 1.0},
#     {'Name': 'Crossbow Heavy', 'Concealability': 'NA', 'Strength': '3+ (STR)S', 'MinDamage': '', 'Weight': 4, 'Base Price': '500¥', 'Legality': '5-D', 'Availability': '6/36 hrs', 'Street Index': 1.0},
#     {'Name': 'Bolts', 'Concealability': 4, 'Strength': 'as crossbow', 'MinDamage': '', 'Weight': 0.05, 'Base Price': '5¥', 'Legality': '10-D', 'Availability': '5/36 hrs', 'Street Index': 1.0},
#     {'Name': 'Throwing Knife', 'Concealability': 9, 'Strength': 'NA', 'MinDamage': '(STR)L', 'Weight': 0.25, 'Base Price': '20¥', 'Legality': '8-D', 'Availability': '2/24 hrs', 'Street Index': 1.0},
#     {'Name': 'Shuriken', 'Concealability': 8, 'Strength': 'NA', 'MinDamage': '(STR)L', 'Weight': 0.25, 'Base Price': '30¥', 'Legality': '6-D', 'Availability': '2/24 hrs', 'Street Index': 2.0}
# ]
#
# accessories_ammunition = [
#     {'Name': 'Regular Ammo', 'Concealability': 8, 'Damage': 'As weapon', 'Weight': 0.5, 'Base Price': '20¥', 'Availability': '2/24 hrs', 'Street Index': 0.75},
#     {'Name': 'Explosive Round', 'Concealability': 8, 'Damage': '+1 Power', 'Weight': 0.75, 'Base Price': '50¥', 'Availability': '3/36 hrs', 'Street Index': 0.8},
#     {'Name': 'Flechette Round', 'Concealability': 8, 'Damage': '+1 to code', 'Weight': 0.5, 'Base Price': '100¥', 'Availability': '3/36 hrs', 'Street Index': 0.8},
#     {'Name': 'Gel Round', 'Concealability': 8, 'Damage': '-2 Power (Stun)', 'Weight': 0.25, 'Base Price': '30¥', 'Availability': '4/48 hrs', 'Street Index': 1.0},
#     {'Name': 'Assault Cannon Ammo', 'Concealability': 3, 'Damage': 'As weapon', 'Weight': 1.25, 'Base Price': '450¥', 'Availability': '5/3 days', 'Street Index': 2.0},
#     {'Name': 'Belt', 'Concealability': 8, 'Damage': 'NA', 'Weight': 12.5, 'Base Price': '4,250¥', 'Availability': '8/3 days', 'Street Index': 2.0},
#     {'Name': 'Taser Dart', 'Concealability': 3, 'Damage': 'As weapon', 'Weight': 0.5, 'Base Price': '50¥', 'Availability': '6/36 hrs', 'Street Index': 1.5},
#     {'Name': 'Taser Cartridge', 'Concealability': 4, 'Damage': 'As weapon', 'Weight': '', 'Base Price': '100¥', 'Availability': '6/36 hrs', 'Street Index': 1.5},
#     {'Name': 'Narcoject Rounds', 'Concealability': 8, 'Damage': 'As weapon', 'Weight': '200¥', 'Base Price': 'As weapon', 'Availability': 'As weapon', 'Street Index': 'As weapon'},
#     {'Name': 'APDS', 'Concealability': 8, 'Damage': '1/2 Ballistic', 'Weight': 0.25, 'Base Price': '70¥', 'Availability': '14/14 days', 'Street Index': 4.0}
# ]
#
# accessories_firearms = [
#     {'Name': 'Concealable Holster', 'Concealability': '+2 to weapon', 'Mount': '', 'Rating': '', 'Weight': 0.1, 'Base Price': '100¥', 'Legality': 'Legal', 'Availability': '2/24 hrs', 'Street Index': 0.75},
#     {'Name': 'Laser Sights', 'Concealability': '-1', 'Mount': 'Top', 'Rating': '', 'Weight': 0.25, 'Base Price': '500¥', 'Legality': 'Legal', 'Availability': '6/36 hrs', 'Street Index': 0.9},
#     {'Name': 'Rangefinder', 'Concealability': '', 'Mount': '', 'Rating': '', 'Weight': 0.1, 'Base Price': '150¥', 'Legality': 'Legal', 'Availability': '2/24 hrs', 'Street Index': 0.8},
#     {'Name': 'Grenade Link', 'Concealability': '', 'Mount': '', 'Rating': '', 'Weight': 0.1, 'Base Price': '750¥', 'Legality': '6-I', 'Availability': '8/48 hrs', 'Street Index': 2.0},
#     {'Name': 'Imaging Scope', 'Concealability': 'Ultrasound-2', 'Mount': 'Top', 'Rating': '', 'Weight': 0.25, 'Base Price': '1,300¥', 'Legality': 'Legal', 'Availability': '8/4 days', 'Street Index': 0.8},
#     {'Name': 'Low-Light', 'Concealability': '-2', 'Mount': 'Top', 'Rating': '', 'Weight': 0.25, 'Base Price': '1,500¥', 'Legality': 'Legal', 'Availability': '3/36 hrs', 'Street Index': 0.8},
#     {'Name': 'Thermographic', 'Concealability': '-2', 'Mount': 'Top', 'Rating': '', 'Weight': 0.25, 'Base Price': '1,500¥', 'Legality': 'Legal', 'Availability': '3/36 hrs', 'Street Index': 0.8},
#     {'Name': 'Magnification 1', 'Concealability': '-1', 'Mount': 'Top', 'Rating': '1', 'Weight': 0.25, 'Base Price': '500¥', 'Legality': 'Legal', 'Availability': '3/36 hrs', 'Street Index': 0.8},
#     {'Name': 'Magnification 2', 'Concealability': '-1', 'Mount': 'Top', 'Rating': '2', 'Weight': 0.25, 'Base Price': '800¥', 'Legality': 'Legal', 'Availability': '3/36 hrs', 'Street Index': 0.9},
#     {'Name': 'Magnification 3', 'Concealability': '-1', 'Mount': 'Top', 'Rating': '3', 'Weight': 0.25, 'Base Price': '1,200¥', 'Legality': 'Legal', 'Availability': '3/36 hrs', 'Street Index': 1.0},
#     {'Name': 'Shock Pads', 'Concealability': '1', 'Mount': '', 'Rating': '', 'Weight': 0.25, 'Base Price': '200¥', 'Legality': 'Legal', 'Availability': '2/24 hrs', 'Street Index': 0.75},
#     {'Name': 'Bipod', 'Concealability': 'Under', 'Mount': '', 'Rating': '2', 'Weight': 2, 'Base Price': '400¥', 'Legality': 'Legal', 'Availability': '6/7 days', 'Street Index': 2.0},
#     {'Name': 'Tripod', 'Concealability': 'Under', 'Mount': '', 'Rating': '8', 'Weight': 8, 'Base Price': '600¥', 'Legality': 'Legal', 'Availability': '10/7 days', 'Street Index': 3.0},
#     {'Name': 'Gas Vent 2-1', 'Concealability': 'Barrel', 'Mount': '', 'Rating': '2', 'Weight': 0.5, 'Base Price': '450¥', 'Legality': 'Legal', 'Availability': '2/24 hrs', 'Street Index': 0.8},
#     {'Name': 'Improved Gas Vent 2', 'Concealability': 'Barrel', 'Mount': '', 'Rating': '2', 'Weight': 0.25, 'Base Price': '550¥', 'Legality': 'Legal', 'Availability': '2/24 hrs', 'Street Index': 0.9},
#     {'Name': 'Gas Vent 3-2', 'Concealability': 'Barrel', 'Mount': '', 'Rating': '3', 'Weight': 0.75, 'Base Price': '700¥', 'Legality': 'Legal', 'Availability': '2/24 hrs', 'Street Index': 0.9},
#     {'Name': 'Improved Gas Vent 3-1', 'Concealability': 'Barrel', 'Mount': '', 'Rating': '3', 'Weight': 0.5, 'Base Price': '800¥', 'Legality': 'Legal', 'Availability': '2/24 hrs', 'Street Index': 0.9},
#     {'Name': 'Improved Gas Vent 4-2', 'Concealability': 'Barrel', 'Mount': '', 'Rating': '4', 'Weight': 0.75, 'Base Price': '1,000¥', 'Legality': 'Legal', 'Availability': '2/24 hrs', 'Street Index': 1.0},
#     {'Name': 'Gyro Mount', 'Concealability': 'Under', 'Mount': '', 'Rating': '5', 'Weight': 6, 'Base Price': '2,500¥', 'Legality': 'Legal', 'Availability': '4/48 hrs', 'Street Index': 1.0},
#     {'Name': 'Improved Gyro Mount', 'Concealability': 'Under', 'Mount': '', 'Rating': '5', 'Weight': 5, 'Base Price': '3,500¥', 'Legality': 'Legal', 'Availability': '6/48 hrs', 'Street Index': 1.0},
#     {'Name': 'Deluxe Gyro Mount', 'Concealability': 'Under', 'Mount': '', 'Rating': '6', 'Weight': 8, 'Base Price': '6,000¥', 'Legality': 'Legal', 'Availability': '4/48 hrs', 'Street Index': 1.0},
#     {'Name': 'Improved Deluxe Gyro Mount', 'Concealability': 'Under', 'Mount': '', 'Rating': '7', 'Weight': 7, 'Base Price': '7,800¥', 'Legality': 'Legal', 'Availability': '6/48 hrs', 'Street Index': 1.0},
#     {'Name': 'Bow Accessory Mount-1', 'Concealability': '', 'Mount': '', 'Rating': '', 'Weight': 0.1, 'Base Price': '100¥', 'Legality': 'Legal', 'Availability': '2/24 hrs', 'Street Index': 0.9},
#     {'Name': 'Spare Clips/Magazines', 'Concealability': '', 'Mount': '', 'Rating': '', 'Weight': 0.75, 'Base Price': '12¥', 'Legality': 'Legal', 'Availability': '2/24 hrs', 'Street Index': 0.75},
#     {'Name': 'Silencer-1', 'Concealability': 'Barrel', 'Mount': '', 'Rating': '2', 'Weight': '', 'Base Price': '500¥', 'Legality': 'As weapon', 'Availability': '4/48 hrs', 'Street Index': 2.0},
#     {'Name': 'Smart Goggles', 'Concealability': 'NA', 'Mount': '', 'Rating': '', 'Weight': 0.1, 'Base Price': '3,000¥', 'Legality': '4P-CA', 'Availability': '3/36 hrs', 'Street Index': 1.0},
#     {'Name': 'Smartgun Adapter-2', 'Concealability': 'Top/under', 'Mount': '', 'Rating': '1', 'Weight': 1.5, 'Base Price': 'x Gun Cost', 'Legality': '4P-CA', 'Availability': '4/48 hrs', 'Street Index': 1.0},
#     {'Name': 'Smartgun Variant', 'Concealability': '', 'Mount': '', 'Rating': '', 'Weight': 0.5, 'Base Price': '2 x Gun Cost + 1/as listed +.5', 'Legality': '', 'Availability': '', 'Street Index': ''},
#     {'Name': 'Ultrasound Goggles', 'Concealability': 'NA', 'Mount': '', 'Rating': '', 'Weight': '', 'Base Price': '1,100¥', 'Legality': 'Legal', 'Availability': '3/36 hrs', 'Street Index': 1.0},
#     {'Name': 'Cyberchoke', 'Concealability': 'NA', 'Mount': '', 'Rating': '', 'Weight': '', 'Base Price': '+10% shotgun cost', 'Legality': '5P-CA', 'Availability': '3/36 hrs', 'Street Index': 1.0}
# ]
#
# equipment_clothing = [
#     {'Name': 'Real Leather', 'Concealability': '0/2', 'Rating': '', 'Weight': 1, 'Base Price': '750¥', 'Legality': 'Legal', 'Availability': 'Always', 'Street Index': 0.75, 'Slot': 'Clothing'},
#     {'Name': 'Synthetic Leather', 'Concealability': '0/1', 'Rating': '', 'Weight': 1, 'Base Price': '250¥', 'Legality': 'Legal', 'Availability': 'Always', 'Street Index': 0.6, 'Slot': 'Clothing'},
#     {'Name': 'Clothing', 'Concealability': '0/0', 'Rating': '', 'Weight': 1, 'Base Price': '50¥', 'Legality': 'Legal', 'Availability': 'Always', 'Street Index': 0.8, 'Slot': 'Clothing'},
#     {'Name': 'Fine Clothing', 'Concealability': '0/0', 'Rating': '', 'Weight': 1, 'Base Price': '500¥', 'Legality': 'Legal', 'Availability': 'Always', 'Street Index': 1.0, 'Slot': 'Clothing'},
#     {'Name': 'Tres Chic Clothing', 'Concealability': '0/0', 'Rating': '', 'Weight': 1, 'Base Price': '1,000¥', 'Legality': 'Legal', 'Availability': 'Always', 'Street Index': 1.0, 'Slot': 'Clothing'}
# ]
#
#
# equipment_armor = [
#     {'Name': 'Armanté Venetian dress', 'Concealability': '14', 'Rating': '1/0', 'Weight': 0.5, 'Base Price': '3,500¥', 'Legality': 'Legal', 'Availability': '1/48 hrs', 'Street Index': 0.75, 'Slot': 'Clothing'},
#     {'Name': 'Armanté Starlight dress', 'Concealability': '13', 'Rating': '1/1', 'Weight': 0.75, 'Base Price': '4,500¥', 'Legality': 'Legal', 'Availability': '2/48 hrs', 'Street Index': 0.75, 'Slot': 'Clothing'},
#     {'Name': 'Armanté Ancien shawl', 'Concealability': '14', 'Rating': '1/0', 'Weight': 0.3, 'Base Price': '570¥', 'Legality': 'Legal', 'Availability': '1/48 hrs', 'Street Index': 0.75, 'Slot': 'Clothing'},
#     {'Name': 'Armanté Executive Tux', 'Concealability': '12', 'Rating': '3/1', 'Weight': 1.0, 'Base Price': '1,100¥', 'Legality': 'Legal', 'Availability': '4/48 hrs', 'Street Index': 0.75, 'Slot': 'Clothing'},
#     {'Name': 'Armanté London Fog cloak', 'Concealability': '12', 'Rating': '2/2', 'Weight': 1.0, 'Base Price': '600¥', 'Legality': 'Legal', 'Availability': '4/48 hrs', 'Street Index': 0.75, 'Slot': 'Clothing'},
#     {'Name': 'Armor Clothing', 'Concealability': '10', 'Rating': '3/0', 'Weight': 2, 'Base Price': '500¥', 'Legality': 'Legal', 'Availability': '2/36 hrs', 'Street Index': 1.0, 'Slot': 'Clothing'},
#     {'Name': 'Armor Jacket', 'Concealability': '7', 'Rating': '5/3', 'Weight': 2, 'Base Price': '900¥', 'Legality': 'Legal', 'Availability': '3/36 hrs', 'Street Index': 0.75, 'Slot': 'Clothing'},
#     {'Name': 'Armor Vest', 'Concealability': '12', 'Rating': '2/1', 'Weight': 1, 'Base Price': '200¥', 'Legality': 'Legal', 'Availability': '2/36 hrs', 'Street Index': 0.8, 'Slot': 'Clothing'},
#     {'Name': 'Greatcoat', 'Concealability': '11', 'Rating': '4/2', 'Weight': 3.0, 'Base Price': '1,000¥', 'Legality': 'Legal', 'Availability': '6/48 hrs', 'Street Index': 0.75, 'Slot': 'Clothing'},
#     {'Name': 'Houndstooth set', 'Concealability': '3/3', 'Rating': '', 'Weight': 2.0, 'Base Price': '2,000¥', 'Legality': 'Legal', 'Availability': '6/48 hrs', 'Street Index': 0.75, 'Slot': 'Clothing'},
#     {'Name': 'Lined Coat', 'Concealability': '8', 'Rating': '4/2', 'Weight': 1, 'Base Price': '700¥', 'Legality': 'Legal', 'Availability': '2/24 hrs', 'Street Index': 0.75, 'Slot': 'Clothing'},
#     {'Name': 'Secure Clothing', 'Concealability': '12', 'Rating': '3/0', 'Weight': 1.5, 'Base Price': '450¥', 'Legality': 'Legal', 'Availability': '3/36 hrs', 'Street Index': 0.9, 'Slot': 'Clothing'},
#     {'Name': 'Secure Jacket', 'Concealability': '9', 'Rating': '5/3', 'Weight': 3, 'Base Price': '850¥', 'Legality': 'Legal', 'Availability': '4/36 hrs', 'Street Index': 0.8, 'Slot': 'Clothing'},
#     {'Name': 'Secure Vest', 'Concealability': '15', 'Rating': '2/1', 'Weight': 0.75, 'Base Price': '175¥', 'Legality': 'Legal', 'Availability': '3/36 hrs', 'Street Index': 0.9, 'Slot': 'Clothing'},
#     {'Name': 'Secure Ultra-Vest', 'Concealability': '14', 'Rating': '4/3', 'Weight': 2.5, 'Base Price': '350¥', 'Legality': 'Legal', 'Availability': '4/36 hrs', 'Street Index': 0.9, 'Slot': 'Clothing'},
#     {'Name': 'Secure Long Coat', 'Concealability': '10', 'Rating': '4/2', 'Weight': 2, 'Base Price': '650¥', 'Legality': 'Legal', 'Availability': '3/36 hrs', 'Street Index': 0.9, 'Slot': 'Clothing'},
#     {'Name': 'Vest With Plates', 'Concealability': '10', 'Rating': '4/3', 'Weight': 2, 'Base Price': '600¥', 'Legality': 'Legal', 'Availability': '3/36 hrs', 'Street Index': 1.0, 'Slot': 'Clothing'},
#     {'Name': 'Zoé Retrovision skirt suit', 'Concealability': '13', 'Rating': '3/1', 'Weight': 1.5, 'Base Price': '2,500¥', 'Legality': 'Legal', 'Availability': '4/48 hrs', 'Street Index': 0.75, 'Slot': 'Clothing'},
#     {'Name': 'Zoé Country Club blazer', 'Concealability': '13', 'Rating': '3/1', 'Weight': 1.0, 'Base Price': '2,000¥', 'Legality': 'Legal', 'Availability': '4/48 hrs', 'Street Index': 0.75, 'Slot': 'Clothing'},
#     {'Name': 'Zoé Highland Laird kilt', 'Concealability': '14', 'Rating': '4/2', 'Weight': 1.5, 'Base Price': '2,000¥', 'Legality': 'Legal', 'Availability': '6/48 hrs', 'Street Index': 0.75, 'Slot': 'Clothing'},
#     {'Name': 'Form-Fitting Body Armor Level 1', 'Concealability': '2/0', 'Rating': '', 'Weight': 0.75, 'Base Price': '150¥', 'Legality': 'Legal', 'Availability': '3/48 hrs', 'Street Index': 1.0, 'Slot': 'Body Armor'},
#     {'Name': 'Form-Fitting Body Armor Level 2', 'Concealability': '15', 'Rating': '3/1', 'Weight': 1.25, 'Base Price': '250¥', 'Legality': 'Legal', 'Availability': '4/48 hrs', 'Street Index': 1.0, 'Slot': 'Body Armor'},
#     {'Name': 'Form-Fitting Body Armor Level 3', 'Concealability': '12', 'Rating': '4/1', 'Weight': 1.75, 'Base Price': '500¥', 'Legality': 'Legal', 'Availability': '4/48 hrs', 'Street Index': 1.0, 'Slot': 'Body Armor'},
#     {'Name': 'Forearm Guards', 'Concealability': '12', 'Rating': '0/1', 'Weight': 0.2, 'Base Price': '250¥', 'Legality': 'Legal', 'Availability': '5/36 hrs', 'Street Index': 0.75, 'Slot': 'Clothing'},
#     {'Name': 'Partial Suit', 'Concealability': 'NA', 'Rating': '6/4', 'Weight': '10+Body', 'Base Price': '10,000¥', 'Legality': '4P-K', 'Availability': '8/10 days', 'Street Index': 2.0, 'Slot': 'Clothing'},
#     {'Name': 'Full Suit', 'Concealability': 'NA', 'Rating': '8/6', 'Weight': '15+Body', 'Base Price': '20,000¥', 'Legality': '2P-K', 'Availability': '16/14 days', 'Street Index': 3.0, 'Slot': 'Clothing'},
#     {'Name': 'Light Security', 'Concealability': 'NA', 'Rating': '6/4', 'Weight': '9+Body', 'Base Price': '7,500¥', 'Legality': '4P-K', 'Availability': '12/10 days', 'Street Index': 2.0, 'Slot': 'Clothing'},
#     {'Name': 'Medium Security', 'Concealability': 'NA', 'Rating': '6/5', 'Weight': '11+body', 'Base Price': '9,000¥', 'Legality': '3P-K', 'Availability': '14/10 days', 'Street Index': 2.5, 'Slot': 'Clothing'},
#     {'Name': 'Heavy Security', 'Concealability': 'NA', 'Rating': '7/5', 'Weight': '13+body', 'Base Price': '12,000¥', 'Legality': '2P-K', 'Availability': '16/14 days', 'Street Index': 3.0, 'Slot': 'Clothing'},
#     {'Name': 'Security Helmet', 'Concealability': 'NA', 'Rating': '1/2', 'Weight': '', 'Base Price': '250¥', 'Legality': '(-1)P-K', 'Availability': '12/14 days', 'Street Index': 2.0, 'Slot': 'Headgear'},
#     {'Name': 'Helmet', 'Concealability': 'NA', 'Rating': '1/1', 'Weight': '', 'Base Price': 'Z00¥', 'Legality': '(-1)P-K', 'Availability': '12/14 days', 'Street Index': 1.5, 'Slot': 'Headgear'},
#     {'Name': 'Small Riot Shield', 'Concealability': 'NA', 'Rating': '+1/0', 'Weight': 2, 'Base Price': '1,500¥', 'Legality': 'Legal', 'Availability': '8/14 days', 'Street Index': 2.0, 'Slot': 'Shield'},
#     {'Name': 'Large Riot Shield', 'Concealability': 'NA', 'Rating': '+2/0', 'Weight': 3, 'Base Price': '3,200¥', 'Legality': 'Legal', 'Availability': '8/14 days', 'Street Index': 2.0, 'Slot': 'Shield'}
# ]
#
#
# weapons_grenades = [
#     {'Name': 'Offensive', 'Concealability': '6', 'Damage': '10S', 'Weight': 0.25, 'Base Price': '30¥', 'Legality': '3-I', 'Availability': '4/4 days', 'Street Index': 2.0},
#     {'Name': 'Defensive', 'Concealability': '6', 'Damage': '10S', 'Weight': 0.25, 'Base Price': '30¥', 'Legality': '3-I', 'Availability': '4/4 days', 'Street Index': 2.0},
#     {'Name': 'Concussion', 'Concealability': '6', 'Damage': '12M stun', 'Weight': 0.25, 'Base Price': '30¥', 'Legality': '3-I', 'Availability': '5/4 days', 'Street Index': 2.0},
#     {'Name': 'Mini-grenade', 'Concealability': '8', 'Damage': 'as grenade', 'Weight': 0.1, 'Base Price': '50¥', 'Legality': '2-I', 'Availability': '8/4 days', 'Street Index': 2.0},
#     {'Name': 'Gas (Neuro-Stun Vll)', 'Concealability': '5', 'Damage': '8S (stun)', 'Weight': 0.25, 'Base Price': '60¥', 'Legality': '3-I', 'Availability': '8/4 days', 'Street Index': 2.0},
#     {'Name': 'Air-timed Mini-grenade', 'Concealability': '8', 'Damage': 'as grenade', 'Weight': 0.05, 'Base Price': '150¥', 'Legality': '2-I', 'Availability': '10/4 days', 'Street Index': 2.0},
#     {'Name': 'Smoke', 'Concealability': '5', 'Damage': 'special', 'Weight': 0.25, 'Base Price': '40¥', 'Legality': 'Legal', 'Availability': '3/36 hrs', 'Street Index': 1.0},
#     {'Name': 'Flash Grenade', 'Concealability': '6', 'Damage': 'special', 'Weight': 0.25, 'Base Price': '40¥', 'Legality': '2-I', 'Availability': '4/48 hrs', 'Street Index': 1.0},
#     {'Name': 'Flash-Pak', 'Concealability': '12', 'Damage': 'special', 'Weight': 0.2, 'Base Price': '250¥', 'Legality': 'Legal', 'Availability': '3/36 hrs', 'Street Index': 1.0}
# ]
#
# weapons_explosives = [
#     {'Name': 'Commercial', 'Concealability': '6', 'Damage': '3', 'Weight': 1, 'Base Price': '60¥', 'Legality': '4P-I', 'Availability': '6/48 hrs', 'Street Index': 1.0},
#     {'Name': 'Plastic, Compound', 'Concealability': '4', 'Damage': '6', 'Weight': 1, 'Base Price': '80¥', 'Legality': '4-I', 'Availability': '8/48 hrs', 'Street Index': 1.0},
#     {'Name': 'Plastic, Compound', 'Concealability': '12', 'Damage': '6', 'Weight': 1, 'Base Price': '200¥', 'Legality': '3-I', 'Availability': '10/48 hrs', 'Street Index': 2.0},
#     {'Name': 'Timer', 'Concealability': '6', 'Damage': '0.25', 'Weight': 100, 'Base Price': '100¥', 'Legality': '6-I', 'Availability': '4/48 hrs', 'Street Index': 2.0},
#     {'Name': 'Radio Detonator', 'Concealability': '8', 'Damage': '0.5', 'Weight': 250, 'Base Price': '250¥', 'Legality': '6-I', 'Availability': '4/48 hrs', 'Street Index': 2.0}
# ]
#
# items_cyberware = [
#     {'Name': 'Bone Lacing', 'Essence': 0.5, 'Cost': '7,500¥', 'Base Price': 'B', 'Type': 'Legal', 'Legality': '6P-CA 5/14 days', 'Slot': 'Bone'},
#     {'Name': 'Aluminum Bone Lacing', 'Essence': 1.15, 'Cost': '25,000¥', 'Base Price': 'B', 'Type': 'Legal', 'Legality': '6P-CB 5/14 days', 'Slot': 'Bone'},
#     {'Name': 'Titanium Bone Lacing', 'Essence': 2.25, 'Cost': '75,000¥', 'Base Price': 'B', 'Type': 'Legal', 'Legality': '6-CC 5/14 days', 'Slot': 'Bone'},
#     {'Name': 'Boosted Reflexes Level 1', 'Essence': 0.5, 'Cost': '15,000¥', 'Base Price': 'B', 'Type': 'Legal', 'Legality': '8P-CB 3/24hrs', 'Slot': 'Nervous System'},
#     {'Name': 'Boosted Reflexes Level 2', 'Essence': 1.25, 'Cost': '40,000¥', 'Base Price': 'B', 'Type': 'Legal', 'Legality': '6P-CB 3/24 hrs', 'Slot': 'Nervous System'},
#     {'Name': 'Boosted Reflexes Level 3', 'Essence': 2.8, 'Cost': '90,000¥', 'Base Price': 'B', 'Type': 'Legal', 'Legality': '5P-CB 3/24 hrs', 'Slot': 'Nervous System'},
#     {'Name': 'Chemical Analyzer', 'Essence': 0.2, 'Cost': '2,500¥/Level', 'Base Price': 'I', 'Type': 'Legal', 'Legality': '4/6 days', 'Slot': 'Cyberware'},
#     {'Name': 'Chipjack', 'Essence': 0.2, 'Cost': '1,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '3/72 hrs', 'Slot': 'Datajack'},
#     {'Name': 'Commlink II', 'Essence': 0.3, 'Cost': '8,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '2/48 hrs', 'Slot': 'Cyberware'},
#     {'Name': 'Commlink IV', 'Essence': 0.3, 'Cost': '18,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '3/48 hrs', 'Slot': 'Cyberware'},
#     {'Name': 'Commlink VIII', 'Essence': 0.3, 'Cost': '40,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '4/48 hrs', 'Slot': 'Cyberware'},
#     {'Name': 'Commlink X', 'Essence': 0.3, 'Cost': '60,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '5/48 hrs', 'Slot': 'Cyberware'},
#     {'Name': 'Cortex Bomb', 'Essence': 'Unknown', 'Cost': '500,000¥', 'Base Price': 'I', 'Type': 'Unknown', 'Legality': '2-CC 20/14 days', 'Slot': 'Unknown'},
#     {'Name': 'Crypto Circuit HD', 'Essence': 'Unknown', 'Cost': 'Level x 10,000¥', 'Base Price': 'H', 'Type': 'Unknown', 'Legality': '4P-CA 6/36 hrs', 'Slot': 'Unknown'},
#     {'Name': 'Data Filter', 'Essence': 0.3, 'Cost': '5,000¥', 'Base Price': 'I', 'Type': 'Legal', 'Legality': '6/36 hrs', 'Slot': 'Cyberware'},
#     {'Name': 'Data Lock', 'Essence': 0.2, 'Cost': '1,000¥', 'Base Price': 'I', 'Type': 'Legal', 'Legality': '6/36 hrs', 'Slot': 'Cyberware'},
#     {'Name': 'Datajack Level 1', 'Essence': 0.1, 'Cost': '500¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': 'Always', 'Slot': 'Datajack'},
#     {'Name': 'Datajack Level 2', 'Essence': 0.15, 'Cost': '1,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': 'Always', 'Slot': 'Datajack'},
#     {'Name': 'Datajack Level 3', 'Essence': 0.2, 'Cost': '2,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': 'Always', 'Slot': 'Datajack'},
#     {'Name': 'Datajack Level 4', 'Essence': 0.25, 'Cost': '4,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': 'Always', 'Slot': 'Datajack'},
#     {'Name': 'Datajack (SR rules)', 'Essence': 0.2, 'Cost': '1,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': 'Always', 'Slot': 'Datajack'},
#     {'Name': 'Datasoft Link', 'Essence': 0.1, 'Cost': '1,000¥', 'Base Price': 'I', 'Type': 'Legal', 'Legality': '3/24 hrs', 'Slot': 'Cyberware'},
#     {'Name': 'Dermal Plating Level 1', 'Essence': 0.5, 'Cost': '6,000¥', 'Base Price': 'B', 'Type': 'Legal', 'Legality': '6P-CA 4/12 days', 'Slot': 'Skin'},
#     {'Name': 'Dermal Plating Level 2', 'Essence': 1.0, 'Cost': '15,000¥', 'Base Price': 'B', 'Type': 'Legal', 'Legality': '6P-CA 4/12 days', 'Slot': 'Skin'},
#     {'Name': 'Dermal Plating Level 3', 'Essence': 1.5, 'Cost': '45,000¥', 'Base Price': 'B', 'Type': 'Legal', 'Legality': '5P-CA 4/12 days', 'Slot': 'Skin'},
#     {'Name': 'Display Link', 'Essence': 0.1, 'Cost': '1,000¥', 'Base Price': 'I', 'Type': 'Legal', 'Legality': '4/36 hrs', 'Slot': 'Cyberware'},
#     {'Name': 'Ears Cyber Replacement', 'Essence': 0.3, 'Cost': '4,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '2/24 hrs', 'Slot': 'Ears'},
#     {'Name': 'Ears Modification', 'Essence': 0.1, 'Cost': '2,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '2/24 hrs', 'Slot': 'Ears'},
#     {'Name': 'Ears Cosmetic Modification', 'Essence': 1, 'Cost': '1,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '2/24 hrs', 'Slot': 'Ears'},
#     {'Name': 'Ears Hearing Amplification', 'Essence': 0.2, 'Cost': '3,500¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '4/48 hrs', 'Slot': 'Ears'},
#     {'Name': 'Ears Damper', 'Essence': 0.1, 'Cost': '3,500¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '4/48 hrs', 'Slot': 'Ears'},
#     {'Name': 'Ears High Frequency', 'Essence': 0.2, 'Cost': '3,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '4/48 hrs', 'Slot': 'Ears'},
#     {'Name': 'Ears Low Frequency', 'Essence': 0.2, 'Cost': '3,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '4/48 hrs', 'Slot': 'Ears'},
#     {'Name': 'Ears Select Sound Filter', 'Essence': 0.2, 'Cost': 'Level x 10,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '6/48 hrs', 'Slot': 'Ears'},
#     {'Name': 'Ears Recorder', 'Essence': 0.3, 'Cost': '7,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '12P-CA 8/48 hrs', 'Slot': 'Ears'},
#     {'Name': 'Encephalon Level 1', 'Essence': 0.5, 'Cost': '15,000¥', 'Base Price': 'I', 'Type': 'Legal', 'Legality': '6/12 days', 'Slot': 'Nervous System'},
#     {'Name': 'Encephalon Level 2', 'Essence': 0.75, 'Cost': '40,000¥', 'Base Price': 'I', 'Type': 'Legal', 'Legality': '6/12 days', 'Slot': 'Nervous System'},
#     {'Name': 'Encephalon Level 3', 'Essence': 1.5, 'Cost': '75,000¥', 'Base Price': 'I', 'Type': 'Legal', 'Legality': '6/12 days', 'Slot': 'Nervous System'},
#     {'Name': 'Encephalon Level 4', 'Essence': 1.75, 'Cost': '115,000¥', 'Base Price': 'I', 'Type': 'Legal', 'Legality': '6/12 days', 'Slot': 'Nervous System'},
#     {'Name': 'Eyes Cyber Replacement', 'Essence': 0.2, 'Cost': '5,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '2/24 hrs', 'Slot': 'Eyes'},
#     {'Name': 'Eyes Camera', 'Essence': 0.4, 'Cost': '5,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '6/24 hrs', 'Slot': 'Eyes'},
#     {'Name': 'Eyes Cosmetic Modification', 'Essence': 1, 'Cost': '1,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '2/24 hrs', 'Slot': 'Eyes'},
#     {'Name': 'Eyes Optical Magnification 1', 'Essence': 0.2, 'Cost': '2,500¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '4/48 hrs', 'Slot': 'Eyes'},
#     {'Name': 'Eyes Optical Magnification 2', 'Essence': 0.2, 'Cost': '4,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '4/48 hrs', 'Slot': 'Eyes'},
#     {'Name': 'Eyes Optical Magnification 3', 'Essence': 0.2, 'Cost': '6,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '4/48 hrs', 'Slot': 'Eyes'},
#     {'Name': 'Eyes Electronic Magnification 1', 'Essence': 0.1, 'Cost': '3,500¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '5/48 hrs', 'Slot': 'Eyes'},
#     {'Name': 'Eyes Electronic Magnification 2', 'Essence': 0.1, 'Cost': '7,500¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '5/48 hrs', 'Slot': 'Eyes'},
#     {'Name': 'Eyes Electronic Magnification 3', 'Essence': 0.1, 'Cost': '11,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '5/48 hrs', 'Slot': 'Eyes'},
#     {'Name': 'Eyes Rangefinder', 'Essence': 0.1, 'Cost': '2,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '8/48 hrs', 'Slot': 'Eyes'},
#     {'Name': 'Eyes Flare Compensation', 'Essence': 0.1, 'Cost': '2,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '5/48 hrs', 'Slot': 'Eyes'},
#     {'Name': 'Eyes Low-Light', 'Essence': 0.2, 'Cost': '3,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '4/36 hrs', 'Slot': 'Eyes'},
#     {'Name': 'Eyes Retinal Duplication Rating 1', 'Essence': 0.1, 'Cost': '50,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '3-CA 12/7 days', 'Slot': 'Eyes'},
#     {'Name': 'Eyes Retinal Duplication Rating 2-4', 'Essence': 0.25, 'Cost': '50,000¥ + (Rating x 25,000¥)', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '3-CA 12/7 days', 'Slot': 'Eyes'},
#     {'Name': 'Eyes Retinal Duplication Rating 5+', 'Essence': 0.5, 'Cost': '50,000¥ + (Rating x 25,000¥)', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '2-CA 12/7 days', 'Slot': 'Eyes'},
#     {'Name': 'Eyes Thermographic', 'Essence': 0.2, 'Cost': '3,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '4/36 hrs', 'Slot': 'Eyes'},
#     {'Name': 'Eyecrafters Opticam Package', 'Essence': 0.5, 'Cost': '20,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '6/40 hrs', 'Slot': 'Eyes'},
#     {'Name': 'Dr. Spott Smartcam Implant', 'Essence': 0.2, 'Cost': '10,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '8/48 hrs', 'Slot': 'Eyes'},
#     {'Name': 'Filtration Systems Air', 'Essence': 'Level/10', 'Cost': 'Level x 15,000¥', 'Base Price': 'B', 'Type': 'Legal', 'Legality': '6/4 days', 'Slot': 'Respiratory System'},
#     {'Name': 'Filtration Systems Blood', 'Essence': 'Level/5', 'Cost': 'Level x 10,000¥', 'Base Price': 'B', 'Type': 'Legal', 'Legality': '6/4 days', 'Slot': 'Blood'},
#     {'Name': 'Filtration Systems Ingested Toxin', 'Essence': 'Level/5', 'Cost': 'Level x 10,000¥', 'Base Price': 'B', 'Type': 'Legal', 'Legality': '6/4 days', 'Slot': 'Digestive System'},
#     {'Name': 'Gas Spectrometer', 'Essence': 0.2, 'Cost': '2,000¥ x Level', 'Base Price': 'I', 'Type': 'Legal', 'Legality': '4/5 days', 'Slot': 'Cyberware'},
#     {'Name': 'Hardening', 'Essence': 0.3, 'Cost': 'See Text (STech pg 56)', 'Base Price': 'M', 'Type': 'Varies', 'Legality': 'Varies/8 days', 'Slot': 'Skin'},
#     {'Name': 'Hydraulic Jack', 'Essence': 0.25, 'Cost': 'Level x 5,000¥', 'Base Price': 'B', 'Type': 'Legal', 'Legality': '5/6 days', 'Slot': 'Muscle/Bone'},
#     {'Name': 'Internal Voice Mask', 'Essence': 0.1, 'Cost': '7,000¥', 'Base Price': 'I', 'Type': 'Legal', 'Legality': '6-CA 6/48 hrs', 'Slot': 'Vocal'},
#     {'Name': 'Limbs Simple Replacement', 'Essence': 1.0, 'Cost': '50,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '3-CA 12/24 days', 'Slot': 'Limbs'},
#     {'Name': 'Memory Recorder', 'Essence': 0.2, 'Cost': '4,000¥', 'Base Price': 'I', 'Type': 'Legal', 'Legality': '4/12 days', 'Slot': 'Cyberware'},
#     {'Name': 'Muscle Augmentation Level 1', 'Essence': 0.5, 'Cost': '8,000¥', 'Base Price': 'B', 'Type': 'Legal', 'Legality': '5/6 days', 'Slot': 'Muscle/Bone'},
#     {'Name': 'Muscle Augmentation Level 2', 'Essence': 1.0, 'Cost': '20,000¥', 'Base Price': 'B', 'Type': 'Legal', 'Legality': '5/6 days', 'Slot': 'Muscle/Bone'},
#     {'Name': 'Muscle Augmentation Level 3', 'Essence': 2.0, 'Cost': '50,000¥', 'Base Price': 'B', 'Type': 'Legal', 'Legality': '5/6 days', 'Slot': 'Muscle/Bone'},
#     {'Name': 'Muscle Augmentation Level 4', 'Essence': 2.5, 'Cost': '90,000¥', 'Base Price': 'B', 'Type': 'Legal', 'Legality': '5/6 days', 'Slot': 'Muscle/Bone'},
#     {'Name': 'Muscle Augmentation Level 5', 'Essence': 3.0, 'Cost': '125,000¥', 'Base Price': 'B', 'Type': 'Legal', 'Legality': '5/6 days', 'Slot': 'Muscle/Bone'},
#     {'Name': 'Muscle Replacement', 'Essence': 1.5, 'Cost': '15,000¥ x Level', 'Base Price': 'B', 'Type': 'Legal', 'Legality': '3/6 days', 'Slot': 'Muscle/Bone'},
#     {'Name': 'Muscle Toner Level 1', 'Essence': 0.25, 'Cost': '8,000¥', 'Base Price': 'B', 'Type': 'Legal', 'Legality': '5/6 days', 'Slot': 'Muscle/Bone'},
#     {'Name': 'Muscle Toner Level 2', 'Essence': 0.5, 'Cost': '20,000¥', 'Base Price': 'B', 'Type': 'Legal', 'Legality': '5/6 days', 'Slot': 'Muscle/Bone'},
#     {'Name': 'Muscle Toner Level 3', 'Essence': 1.0, 'Cost': '50,000¥', 'Base Price': 'B', 'Type': 'Legal', 'Legality': '5/6 days', 'Slot': 'Muscle/Bone'},
#     {'Name': 'Muscle Toner Level 4', 'Essence': 1.5, 'Cost': '90,000¥', 'Base Price': 'B', 'Type': 'Legal', 'Legality': '5/6 days', 'Slot': 'Muscle/Bone'},
#     {'Name': 'Muscle Toner Level 5', 'Essence': 2.0, 'Cost': '125,000¥', 'Base Price': 'B', 'Type': 'Legal', 'Legality': '5/6 days', 'Slot': 'Muscle/Bone'},
#     {'Name': 'Nanites (SR5, R4)', 'Essence': 0.1, 'Cost': '5,000¥', 'Base Price': 'I', 'Type': 'Legal', 'Legality': 'Always', 'Slot': 'Nanoware'},
#     {'Name': 'Narcoject Injector', 'Essence': 0.1, 'Cost': '500¥', 'Base Price': 'I', 'Type': 'Legal', 'Legality': '6/48 hrs', 'Slot': 'Vascular'},
#     {'Name': 'Olfactory Booster', 'Essence': 0.1, 'Cost': '1,500¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '2/24 hrs', 'Slot': 'Olfactory'},
#     {'Name': 'Olfactory Booster 2', 'Essence': 0.1, 'Cost': '5,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '2/24 hrs', 'Slot': 'Olfactory'},
#     {'Name': 'Olfactory Booster 3', 'Essence': 0.1, 'Cost': '10,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '2/24 hrs', 'Slot': 'Olfactory'},
#     {'Name': 'Olfactory Booster 4', 'Essence': 0.1, 'Cost': '15,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '2/24 hrs', 'Slot': 'Olfactory'},
#     {'Name': 'Olfactory Booster 5', 'Essence': 0.1, 'Cost': '20,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '2/24 hrs', 'Slot': 'Olfactory'},
#     {'Name': 'Platelet Factories', 'Essence': 0.4, 'Cost': '10,000¥ x Level', 'Base Price': 'I', 'Type': 'Legal', 'Legality': '4/6 days', 'Slot': 'Vascular'},
#     {'Name': 'Pulmonary Booster', 'Essence': 0.1, 'Cost': '10,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '3/12 hrs', 'Slot': 'Respiratory System'},
#     {'Name': 'Reaction Enhancers Level 1', 'Essence': 0.3, 'Cost': '10,000¥', 'Base Price': 'B', 'Type': 'Legal', 'Legality': '5/6 days', 'Slot': 'Nervous System'},
#     {'Name': 'Reaction Enhancers Level 2', 'Essence': 0.6, 'Cost': '30,000¥', 'Base Price': 'B', 'Type': 'Legal', 'Legality': '5/6 days', 'Slot': 'Nervous System'},
#     {'Name': 'Reaction Enhancers Level 3', 'Essence': 1.0, 'Cost': '60,000¥', 'Base Price': 'B', 'Type': 'Legal', 'Legality': '5/6 days', 'Slot': 'Nervous System'},
#     {'Name': 'Recycler', 'Essence': 0.25, 'Cost': '2,000¥', 'Base Price': 'I', 'Type': 'Legal', 'Legality': '6/36 hrs', 'Slot': 'Cyberware'},
#     {'Name': 'Reflex Recorder Level 1', 'Essence': 0.25, 'Cost': '10,000¥', 'Base Price': 'I', 'Type': 'Legal', 'Legality': '6/12 days', 'Slot': 'Nervous System'},
#     {'Name': 'Reflex Recorder Level 2', 'Essence': 0.5, 'Cost': '25,000¥', 'Base Price': 'I', 'Type': 'Legal', 'Legality': '6/12 days', 'Slot': 'Nervous System'},
#     {'Name': 'Reflex Recorder Level 3', 'Essence': 1.0, 'Cost': '50,000¥', 'Base Price': 'I', 'Type': 'Legal', 'Legality': '6/12 days', 'Slot': 'Nervous System'},
#     {'Name': 'Reflex Recorder Level 4', 'Essence': 1.5, 'Cost': '80,000¥', 'Base Price': 'I', 'Type': 'Legal', 'Legality': '6/12 days', 'Slot': 'Nervous System'},
#     {'Name': 'Sleep Regulator', 'Essence': 0.1, 'Cost': '20,000¥', 'Base Price': 'I', 'Type': 'Legal', 'Legality': '2/48 hrs', 'Slot': 'Nervous System'},
#     {'Name': 'Smartlink', 'Essence': 0.2, 'Cost': '2,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '5/48 hrs', 'Slot': 'Eyes'},
#     {'Name': 'Skillwires Level 1', 'Essence': 0.3, 'Cost': '20,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '4/24 hrs', 'Slot': 'Nervous System'},
#     {'Name': 'Skillwires Level 2', 'Essence': 0.6, 'Cost': '50,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '4/24 hrs', 'Slot': 'Nervous System'},
#     {'Name': 'Skillwires Level 3', 'Essence': 1.0, 'Cost': '100,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '4/24 hrs', 'Slot': 'Nervous System'},
#     {'Name': 'Skillwires Level 4', 'Essence': 1.5, 'Cost': '150,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '4/24 hrs', 'Slot': 'Nervous System'},
#     {'Name': 'Skillwires Level 5', 'Essence': 2.0, 'Cost': '200,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '4/24 hrs', 'Slot': 'Nervous System'},
#     {'Name': 'Sleep Regulator', 'Essence': 0.1, 'Cost': '20,000¥', 'Base Price': 'I', 'Type': 'Legal', 'Legality': '2/48 hrs', 'Slot': 'Nervous System'},
#     {'Name': 'Tailored Pheromones Level 1', 'Essence': 0.2, 'Cost': '10,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '3/48 hrs', 'Slot': 'Nervous System'},
#     {'Name': 'Tailored Pheromones Level 2', 'Essence': 0.5, 'Cost': '25,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '3/48 hrs', 'Slot': 'Nervous System'},
#     {'Name': 'Tailored Pheromones Level 3', 'Essence': 1.0, 'Cost': '50,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '3/48 hrs', 'Slot': 'Nervous System'},
#     {'Name': 'Toxin Extractor', 'Essence': 0.25, 'Cost': '15,000¥', 'Base Price': 'I', 'Type': 'Legal', 'Legality': '3/5 days', 'Slot': 'Digestive System'},
#     {'Name': 'Toxin Filtration', 'Essence': 0.1, 'Cost': '8,000¥', 'Base Price': 'I', 'Type': 'Legal', 'Legality': '5/4 days', 'Slot': 'Digestive System'},
#     {'Name': 'Toxin Seal', 'Essence': 0.25, 'Cost': '10,000¥', 'Base Price': 'I', 'Type': 'Legal', 'Legality': '4/5 days', 'Slot': 'Digestive System'},
#     {'Name': 'Vocal Range Enhancer', 'Essence': 0.1, 'Cost': '5,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '6/48 hrs', 'Slot': 'Vocal'},
#     {'Name': 'Voice Modulator', 'Essence': 0.2, 'Cost': '10,000¥', 'Base Price': 'H', 'Type': 'Legal', 'Legality': '6/48 hrs', 'Slot': 'Vocal'}
# ]
#
# items_genetec = {
#     'Name': ['Antibac', 'Binder', 'Doom', 'Gamma-Anthrax', 'Gene Therapy', 'Genetic Correction', 'Reconstnuct/Healing', 'Immunization', 'Léonization', 'Myco-Protein', 'Zeta-Interpheron'],
#     'Effect': ['Level 1-3 reduces power of pathogens by rating injection', 'Level 1-3 reduces power of specific chemical by rating injection', '6M, special special air,contact', '6S Stun varies air,con,inj', 'Cleansing 1 month', '6 months', '4 months', 'Single pathogen or chemical', 'reverses effects of aging', 'foodstuff', 'Level 1-3 reduces power of specific virus by rating injection'],
#     'Speed': ['-', '-', '6', '6', '-', '-', '-', '-', '-', '-', '-'],
#     'Vector': ['-', '-', 'M', 'S', '-', '-', '-', '-', '-', '-', '-'],
#     'Base Price': ['Level x 500¥', 'Level x 300¥', '500¥/dose', '180¥/dose', '50,000¥', '60,000¥', '100,000¥', '40,000¥ per treatment', '2,000,000¥+', '25¥/kg', 'Level x 400¥'],
#     'Legality': ['Legal', 'Legal', '1-M3', '2-M3', 'Legal', 'Legal', 'Legal', 'Legal', '100,000¥', 'Legal', 'Legal'],
#     'Availability': ['4/48 hrs', '4/32 hrs', '14/30 days', '14/30 days', '6/30 days', '6/30 days', '6/30 days', '6/20 days', '6/30 days', "It's everywhere", '4/32 hrs'],
#     'Street Index': [1.0, 2.0, 5.0, 6.0, 2.5, 2.5, 2.5, 2.0, 2.5, 8.0, 2.0]
# }
#
# items_drones = {
#     "Name": ["Aerodesign Systems Condor LDSD-23",
#              "Aztechnology GCR-23C Crawler",
#              "CAS Wandjina RPV",
#              "Cyberspace Designs Dalmatian Recon",
#              "GAS-Niki GNRD-71bis Snooper",
#              "GM-Nissan Doberman",
#              "GM-Nissan Spotter",
#              "MCT Nissan Rotodrone",
#              "MCT Nissan Rotodrone (Armed Variant)",
#              "Sikorski-Bell Microskimmer"],
#     "Handling": ["5", "4/4", "3/5", "3", "4/3", "3/5", "3", "4", "4", "5"],
#     "Speed": ["20/60", "5/9", "250/500", "35/105", "25/75", "35/70", "35/100", "35/70", "60/65", "30/90"],
#     "Body/Armor": ["1/0", "1/0", "5/6", "2/0", "1/0", "3/6", "2/0", "2/0", "4/0", "1/0"],
#     "Sig": ["10", "4", "4/8", "4", "5", "3", "3", "3", "4", "3"],
#     "Auto Pilot": ["1", "1", "4", "2", "1", "2", "2", "2", "2", "1"],
#     "Availability": ["8/7 days", "8/4 days", "16/6 mths", "6/4 days", "8/4 days", "8/14 days", "6/7 days", "6/1 day", "8/2 days", "5/3 days"],
#     "Cost": ["2,500¥", "1,250¥", "75,000¥", "15,000¥", "1,750¥", "10,000¥", "12,500¥", "7,500¥", "12,500¥", "2,750¥"],
#     "Street Index": ["2.5", "2.0", "3.0", "2.0", "2.0", "2.5", "1.5", "1.2", "1.2", "2.0"]
# }
#
# vehicles_civilian = {
#     "Name": ["Chlysler-Nissan Jackrabbit (el)", "Chlysler-Nissan Jackrabbit (mf)", "Eurocar Westwind 2000", "Ford Americar", "Honda-GM 3220 ZX", "Honda-GM 3220 ZX Turbo", "Leyland-Zil Tsarina (el)", "Leyland-Zil Tsarina (mf)", "Mitsubishi Nightsky", "Mitsubishi Runabout", "Rolls Royce Phaeton", "Saab Dynamit 776TI", "Toyota Elite", "Volkswagon Elektro", "BMW Blitzen", "Dodge Scoot", "Papoose", "Papoose Maximus", "GAZ-Niki White Eagle", "Harley Scorpion", "Honda Viking", "Hyundai Offroader", "Suzuki Aurora", "Thundercloud Pinto Trike", "Yamaha Rapier", "Ford-Canada Bison", "GAZ-Willys Nomad", "Landrover Model 2046, long", "Landrover Model 2046, short", "Leyland-Rover Transport (el)", "Leyland-Rover Transport (ic)", "Nissan-Holden Brumby", "Renault-Fiat Eurovan", "Rolls Royce Prarie Cat", "Toyotacorp Gopher Pickup", "Volkswagon Superkombi III", "Ares Roadmaster™", "Conestoga Trailblazer Prime Mover4/8", "GMC 4201", "GMC Bulldog Step-van", "Courier Variant", "Nordkapp-Conestoga Bergen command module", "Nordkapp-Conestoga Bergen cargo module", "Chrysler-Nissan G12a", "GMC-Beachcraft Vacationer", "GMC-Nissan Hovertruck", "Mostrans Ivan KVP-I4T", "Aztech Niahtrunner", "Colorado Craft Cigarette", "Harland & Wolff Classique Yacht", "Marine Technologies Dolphin II", "Samuvani Chriscraft Otter", "Sendanko Marlin", "Suzuki Watersport (el)", "Suzuki Watersport (ic)", "Zemlya-Poltava Swordsman (ic)", "Acced Electric engines", "Poseidon Engines", "Arrow HSCT", "Cessna C750", "China Clipper Suborbital", "Embraer-Dassault Mistral", "Fiat-Fokker Cloud Nine", "GD SV250 Semiballistic", "Hawker-Siddley HS-895 Skytruck", "Lear-Cessna Platinum I", "Lear-Cessna Platinum II"],
#     "Handling": ["3/8", "3/8", "3/8", "4/8", "4/8", "4/8", "4/8", "4/8", "4/8", "4/8", "4/4", "4/8", "4/8", "3/6", "3/4", "3/6", "3/6", "3/6", "3/3", "4/5", "3/5", "4/2", "2/4", "4/2", "3/2", "4/3", "3/3", "3/3", "3/3", "4/8", "4/8", "4/3", "4/10", "2/3", "4/4", "4/8", "3/6", "4/8", "4/8", "4/8", "3/6", "3/6", "4", "4", "4", "4", "4", "3", "5", "2", "2", "4", "5", "5", "5", "4", "4", "5", "4", "5"],
#     "Speed": ["25/75", "30/90", "70/210", "35/105", "40/120", "50/150", "25/75", "30/90", "45/120", "25/75", "60/180", "80/250", "40/120", "20/60", "95/285", "20/60", "30/90", "30/90", "60/180", "50/150", "50/150", "60/180", "70/210", "20/60", "65/195", "45/135", "30/90", "30/90", "30/90", "25/75", "35/105", "30/90", "35/105", "30/90", "40/120", "35/105", "35/105", "35/85", "35/85", "35/85", "35/105", "35/105", "40/120", "25/75", "35/105", "15/45", "25/75", "15/45", "20/30", "10/30", "15/45", "25/75", "30/90", "1,500/2,900", "340/680", "10,000/24,000", "300/450", "300/450", "10,000/29,000", "400/600", "400/550", "800/1600"],
#     "Body/Armor": ["1/0", "1/0", "2/0", "2/0", "2/0", "2/0", "1/0", "1/0", "5/3", "1/0", "5/10", "2/3", "4/0", "1/0", "3/6", "1/0", "1/0", "2/0", "3/0", "3/3", "4/6", "2/0", "1/0", "3/0", "3/0", "5/6", "3/0", "3/0", "3/0", "3/0", "3/0", "2/0", "3/0", "3/0", "4/0", "5/0", "5/3", "4/0", "5/3", "4/0", "4/0", "4/3", "6/6", "5/3", "5/3", "4/0", "4/0", "4/0", "1/0", "1/0", "3/0", "1/0", "3/0", "3/0", "5/6", "3/0", "3/0", "5/3", "3/0", "3/0", "6/3", "5/0"],
#     "Sig": ["5", "3", "2", "2", "2", "1", "5", "2", "4", "5", "2", "1", "2", "5", "1", "5", "5", "5", "1", "2", "1", "2", "5", "5", "1", "2", "2", "2", "2", "2", "5", "2", "3", "4", "3", "2", "2", "2", "2", "2", "2", "4", "5", "5", "3", "3", "5", "3", "3", "8", "8", "1", "4", "5", "6", "3", "3", "8", "3", "3", "8", "4", "5"],
#     "Auto Pilot": ["1", "1", "3", "2", "1", "2", "1", "1", "4", "1", "4", "3", "4", "Always", "2", "Always", "Always", "Always", "Always", "2", "2", "1", "Always", "Always", "Always", "Always", "Always", "Always", "2", "2", "1", "1", "1", "1", "1", "1", "1", "2", "2", "2", "2", "2", "4", "2", "1", "4", "2", "2", "1", "1", "5", "4", "1", "2", "3", "1"],
#     "Availability": ["-", "-", "4/7 days", "-", "2/2 days", "3/4 days", "-", "-", "4/10 days", "-", "4/14 days", "4/10 days", "3/4 days", "-", "4/10 days", "-", "-", "-", "-", "2/4 days", "2/4 days", "-", "2/2 days", "2/2 days", "-", "4/14 days", "4/14 days", "4/14 days", "4/14 days", "4/14 days", "4/14 days", "4/14 days", "4/14 days", "2/4 days", "6/7 days", "6/7 days", "6/7 days", "6/7 days", "6/14 days", "6/7 days", "6/7 days", "6/7 days", "6/7 days", "2/3 days", "2/7 days", "7/7 days", "4/7 days", "4/14 days", "6/24 days", "4/14 days", "4/7 days", "6/24 days", "7/21 days", "5/21 days", "7/21 days"],
#     "Cost": ["15,000¥", "18,000¥", "100,000¥", "20,000¥", "30,000¥", "45,000¥", "10,000¥", "12,000¥", "250,000¥", "10,000¥", "500,000¥", "250,000¥", "125,000¥", "8,000¥", "25,000¥", "2,000¥", "6,000¥", "12,000¥", "15,000¥", "15,000¥", "17,000¥", "12,500¥", "15,000¥", "35,000¥", "10,000¥", "150,000¥", "50,000¥", "45,000¥", "35,000¥", "25,000¥", "30,000¥", "25,000¥", "275,000¥", "25,000¥", "25,000¥", "45,000¥", "150,000¥", "75,000¥", "35,000¥", "60,000¥", "600,000¥", "200,000¥", "100,000¥", "375,000¥", "175,000¥", "750,000¥", "2,500,000¥", "500,000¥", "1,500,000¥", "200,000¥", "100,000¥", "2,500¥", "200,000¥", "100,000¥", "400,000¥", "700,000¥", "1,000,000¥", "950,000¥", "600,000¥", "625,000¥", "900,000¥", "300,000¥", "100,000¥", "225,000¥", "750,000¥"],
#     "Street Index": ["1.0", "1.0", "0.9", "1.0", "1.0", "1.0", "1.0", "1.0", "0.9", "1.0", "1.0", "0.9", "0.9", "1.0", "1.1", "1.0", "1.0", "1.0", "0.9", "0.7", "0.8", "0.9", "0.9", "0.8", "0.9", "0.7", "0.9", "0.9", "0.9", "0.8", "0.7", "0.8", "1.0", "0.9", "0.9", "0.7", "0.8", "0.9", "0.7", "0.8", "0.8", "0.8", "0.8", "0.8", "0.8", "0.8", "0.8", "0.8", "0.8", "0.8", "0.8", "0.8", "0.8", "0.8", "0.8", "0.8", "0.8", "0.8", "0.8"],
#     "Type": ["car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "bike", "bike", "entertainment", "entertainment", "car", "bike", "bike", "car", "car", "bike", "bike", "car", "truck", "truck", "car", "truck", "truck", "truck", "truck", "car", "truck", "truck", "truck", "truck", "truck", "hovercraft", "hovercraft", "hovercraft", "hovercraft", "boat", "boat", "boat", "boat", "boat", "boat", "boat", "boat", "plane", "plane", "plane", "plane", "plane", "plane", "plane", "plane", "plane", "plane", "plane", "rotorcraft", "rotorcraft", "lighter-than-air"]
# }
#
# vehicles_security = {
#     "Name": ["Ares Citymaster™", "Ares Mobmaster™", "Chrysler-Nissan Patrol-1", "DocWagon™ SRT Ambulance", "DocWagon™ CRT Ambulance", "General Products COP", "Harley Electraglide-I000", "Sikorski-Bell Red Ranger ACV", "Wheels engaged", "Blohm & Voss River Commander", "GMC Riverine", "GMC-Beachcraft Patroller", "Surfstar Marine Seacop", "CASA J-239 Raven", "DocWagon™ SRT Helicopter", "DocWagon™ CRT Helicopter", "DocWagon™ HTR Helicopter", "DocWagon™ HTR Osprey II", "Moonlight Aerospace Avenger", "Northrup PRC-42B Wasp", "Northrup PRC-44B Yellowjacket", "Aztechnology Agular-EX", "BAC-Dassault-MBB EFA variants", "Federated-Boeing Eagle", "Ferrari Appaloosa Light Scout", "GMC Banshee LAV"],
#     "Handling": ["4/10", "4/10", "4/8", "4/10", "4/10", "4/9", "3/4", "4/6", "3/5", "4", "3", "4", "3", "3", "5", "5", "5", "5", "4", "3", "4", "3", "3", "3", "3", "2/3", "3"],
#     "Speed": ["30/120", "30/120", "60/180", "30/75", "30/75", "30/90", "95/285", "150/450", "30/90", "25/75", "30/90", "55/165", "30/90", "200/400", "170/250", "140/320", "165/235", "190/380", "100/200", "65/130", "65/130", "280/560", "950/1900", "900/1800", "100/200", "650/1000"],
#     "Body/Armor": ["4/12", "5/15", "3/6", "4/0", "5/0", "1/3", "3/6", "2/6", "8", "6/9", "4/6", "4/6", "3/6", "3/0", "4/0", "3/0", "5/6", "3/3", "3/9", "1/0", "2/0", "3/6", "4/6", "5/12", "3/9", "6/18"],
#     "Sig": ["2", "2", "4", "2", "2", "4", "2", "3", "1.0", "3", "3", "5", "3", "4", "4", "3", "4", "2", "8", "3", "2", "4", "4", "4", "5", "2", "5"],
#     "Auto Pilot": ["3", "5", "3", "1", "2", "4", "1", "3", "1.0", "3", "3", "2", "3", "4", "3", "3", "4", "3", "2", "3", "3", "4", "4", "4", "2", "3", "3"],
#     "Availability": ["10/14 days", "21/2 mths", "8/10 days", "8/10 days", "10/14 days", "6/7 days", "10/14 days", "10/14 days", "2/3 days", "14/21 days", "12/14 days", "10/14 days", "10/14 days", "16/6 mths", "8/21 days", "10/21 days", "14/28 days", "12/24 days", "16/6 mths", "16/6 mths", "16/6 mths", "14/3 mths", "16/3 mths", "14/3 mths", "16/6 mths", "18/6 mths"],
#     "Cost": ["500,000¥", "3.65M¥", "100,000¥", "100,000¥", "120,000¥", "25,000¥", "75,000¥", "250,000¥", "1,000¥", "300,000¥", "125,000¥", "750,000¥", "50,000¥", "175,000¥", "400,000¥", "700,000¥", "1M¥", "950,000¥", "250,000¥", "220,000¥", "280,000¥", "2.6M¥", "5M¥", "50M¥", "1M¥", "10M¥"],
#     "Street Index": ["2.0", "2.0", "2.0", "2.5", "2.5", "2.5", "2.5", "2.0", "1.0", "2.5", "2.0", "2.0", "2.0", "2.0", "1.5", "2.0", "2.0", "2.5", "2.5", "2.0", "2.0", "2.8", "2.5", "1.5", "3.0", "3.0"],
#     "Type": ["land_vehicle", "land_vehicle", "land_vehicle", "land_vehicle", "land_vehicle", "land_vehicle", "land_vehicle", "land_vehicle", "land_vehicle", "water_vehicle", "water_vehicle", "water_vehicle", "water_vehicle", "air_vehicle", "air_vehicle", "air_vehicle", "air_vehicle", "air_vehicle", "air_vehicle", "air_vehicle", "air_vehicle", "air_vehicle", "air_vehicle", "air_vehicle", "air_vehicle", "air_vehicle", "air_vehicle"]
# }
# }
#
# vehicles_modifications = {
#     "Name": ["Advanced Passenger Protection", "Amphibious Operation Package", "Propeller", "Water jet", "Anti-Theft Systems", "Autopilot", "Bench Seat", "Bench Seat, Folding", "Boat Hull Modifications", "Bucket Seat", "Bucket Seat, Big", "Bucket Seat, Ejection", "Cargo Container", "Convertable Top", "Crash Cage", "Datajack Link", "Drone Rack", "Drop Tanks", "ECM Security", "ECCM Security", "Electronics Bay", "EnviroSeal™", "External Cargo Space", "Flotation Package", "Fujicorp Remote Ignition", "GridLink™ Power", "Headlight Options", "Integrated Controls", "Life Support", "Reinforced Seating", "Reduced Sized Components", "Remote Control Deck", "Remote Control Deck, Cyber", "Remote Control Gear", "Rigger Control Gear", "Roll Bars", "Secondary Controls", "Sensors", "SunCell™ Power", "Tires", "Vehicle Weapon Mounts", "Vehicle Weapon Mounts", "Vehicle Weapon Mounts", "Vehicle Weapon Mounts", "Vehicle Weapon Mounts", "External Rack Mounts", "External Rack Mounts"],
#     "CF": ["1", "", "2", "3", "", "Rating", "5", "5", "", "5", "6", "8", "", "", "7", "2", "+2", "(100L)", "I (Rating 1)", "I (Rating 1)", "", "1", "", "2", "1", "3", "", "2", "1", "1-1", "Rating x 5,000¥", "Rating x 25,000¥", "2", "2", "2", "2", "3", "2", "Standard (Rating 1)", "1", "", "", "1", "1", "1", "1", "2-1", "2-1", "1-1", "1-1", "1-1"],
#     "Installation Time": ["1 week", "Basic", "1 week", "2 weeks", "1 day", "2 days", "1 day", "1 day", "4 days", "1 day", "1 day", "2 days", "", "3 days", "2 days", "1 week", "1 week", "10 miniutes", "2 days", "2 days", "1 day", "1 day", "1 day", "1 day", "4 days", "1 hour", "2 days", "1 day", "1 week", "1 day", "1 day", "1 day", "1 day", "1 day", "1 day", "2 days", "3 days", "2 days", "1 day", "1 per 10 man-hours1 day", "1", "15 minutes", "12 hours", "1 day", "1 day", "1 day", "3 days", "3 days", "1 day", "1 day"],
#     "Required Equip Cost": ["Vehicle Facility 2,500¥", "Vehicle Facility 2,500¥", "Vehicle Facility 7,500¥", "Vehicle Facility 15,000¥", "Vehicle Kit Rating x 100¥", "Vehicle Facility Body x 500¥", "Vehicle Shop 75¥", "Vehicle Shop 50¥", "Vehicle Facility 500¥", "Vehicle Shop 700¥", "Vehicle Shop 750¥", "VehicleFacility 3,000¥", "5,000¥", "Vehicle Shop 10% + 2,500¥", "Vehicle Shop 3,500¥", "Vehicle Facility 2,500¥", "Vehicle Facility 1,000¥", "200¥", "Vehicle Facility 25,000¥", "Vehicle Facility 20,000¥", "Vehicle Facility 70,000¥", "Vehicle Shop 5% of item", "Legal", "10% vehicle Legal", "600¥", "600¥", "Legal", "1,500¥", "1,500¥", "500¥ + 100¥ x Manhours", "250¥", "Level 1-1 Base x 2", "Rating x 5,000¥", "Rating x 25,000¥", "Body x 2,500¥", "1,800¥", "2,000¥", "400¥", "5,000¥", "15,000¥", "45,000¥", "120,000¥", "360,000¥", "700,000¥", "2.0", "500¥", "", "50¥", "1,500¥", "2,000¥", "3,000¥", "1,000¥", "1,750¥", "750¥", "750¥"],
#     "Legality": ["Legal", "Legal", "Legal", "Legal", "Legal Always", "Legal", "Always", "Always", "Legal", "Always", "Always", "", "Always", "Always", "Legal", "Legal", "Legal", "Legal", "Legal", "Legal", "Legal", "Legal", "Legal", "Always", "Legal", "Legal", "Legal", "Legal", "Legal", "Legal", "Always", "Legal", "Legal", "Legal", "Legal", "Legal", "Legal", "Legal", "Legal", "Legal", "Legal", "Legal", "Legal", "Legal", "Legal", "Legal", "Legal", "Legal", "Legal", "Legal"],
#     "Availability": ["2/2 days", "4 days", "1 week", "2 weeks", "1 day", "4/2 days", "Always", "Always", "4/4 days", "2/1 day", "3/1 day", "6/1 week", "Always", "Always", "3/1 day", "5/7 days", "5/7 days", "7/7 days", "8/7 days", "8/1 mth", "10/1 mth", "2/1 day", "4/7 days", "Always", "5/7 days", "2/1 day", "2/1 day", "2/1 day", "4/7 days", "4/7 days", "5/7 days", "3/1 day", "8/7 days", "4/3 days", "4/3 days", "5P-E1 4/3 days", "5P-E1 4/7 days", "4/7 days", "7/8 days", "2/3 days", "2/5 days", "Legal Always", "4/1 day", "4/1 day", "4/1 day", "4/1 day", "4/1 day", "7/7 days", "6/4 days"],
#     "Street Index": ["0.8", "", "1.4", "1.4", "0.75", "1.0", "1.0", "1.0", "1.0", "0.5", "0.5", "1.4", "1.0", "0.8", "0.8", "0.75", "0.75", "1.5", "1.0", "2.0", "2.0", "0.75", "0.75", "1.0", "1.5", "1.5", "1.0", "1.0", "1.2", "1.2", "1.0", "1.0", "2.0", "2.0", "2.0", "2.0", "0.75", "1.0", "0.9", "1.0", "1.0", "1.0", "1.5", "1.5", "1.0", "1.0", "1.0", "1.0", "1.0", "1.5", "1.5"],
#     "ratings_range_low": ["", "", "", "", "1", "1", "", "", "", "", "", "", "", "", "", "", "", "", "1", "1", "", "", "", "", "", "", "", "", "", "1", "1", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
#     "ratings_range_high": ["", "", "", "", "3", "4", "", "", "", "", "", "", "", "", "", "", "", "", "3", "3", "", "", "", "", "", "", "", "", "", "4", "4", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
# }